package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BusinessHours generated by hbm2java
 */
@Entity
@Table(name = "business_hours", catalog = "wollits")
public class BusinessHours implements java.io.Serializable {

	private int businessHourId;
	private Restaurants restaurants;
	private int isoWeekday;
	private String openTime;
	private String openDuration;
	private String closingDuration;

	public BusinessHours() {
	}

	public BusinessHours(int businessHourId, Restaurants restaurants,
			int isoWeekday, String openTime, String openDuration,
			String closingDuration) {
		this.businessHourId = businessHourId;
		this.restaurants = restaurants;
		this.isoWeekday = isoWeekday;
		this.openTime = openTime;
		this.openDuration = openDuration;
		this.closingDuration = closingDuration;
	}

	@Id
	@Column(name = "business_hour_id", unique = true, nullable = false)
	public int getBusinessHourId() {
		return this.businessHourId;
	}

	public void setBusinessHourId(int businessHourId) {
		this.businessHourId = businessHourId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurants getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Restaurants restaurants) {
		this.restaurants = restaurants;
	}

	@Column(name = "iso_weekday", nullable = false)
	public int getIsoWeekday() {
		return this.isoWeekday;
	}

	public void setIsoWeekday(int isoWeekday) {
		this.isoWeekday = isoWeekday;
	}

	@Column(name = "open_time", nullable = false)
	public String getOpenTime() {
		return this.openTime;
	}

	public void setOpenTime(String openTime) {
		this.openTime = openTime;
	}

	@Column(name = "open_duration", nullable = false)
	public String getOpenDuration() {
		return this.openDuration;
	}

	public void setOpenDuration(String openDuration) {
		this.openDuration = openDuration;
	}

	@Column(name = "closing_duration", nullable = false)
	public String getClosingDuration() {
		return this.closingDuration;
	}

	public void setClosingDuration(String closingDuration) {
		this.closingDuration = closingDuration;
	}

}
