package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chains generated by hbm2java
 */
@Entity
@Table(name = "chains", catalog = "wollits")
public class Chains implements java.io.Serializable {

	private int chainId;
	private String name;
	private String urlName;
	private Set<Restaurants> restaurantses = new HashSet<Restaurants>(0);

	public Chains() {
	}

	public Chains(int chainId, String name, String urlName) {
		this.chainId = chainId;
		this.name = name;
		this.urlName = urlName;
	}

	public Chains(int chainId, String name, String urlName,
			Set<Restaurants> restaurantses) {
		this.chainId = chainId;
		this.name = name;
		this.urlName = urlName;
		this.restaurantses = restaurantses;
	}

	@Id
	@Column(name = "chain_id", unique = true, nullable = false)
	public int getChainId() {
		return this.chainId;
	}

	public void setChainId(int chainId) {
		this.chainId = chainId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url_name", nullable = false)
	public String getUrlName() {
		return this.urlName;
	}

	public void setUrlName(String urlName) {
		this.urlName = urlName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chains")
	public Set<Restaurants> getRestaurantses() {
		return this.restaurantses;
	}

	public void setRestaurantses(Set<Restaurants> restaurantses) {
		this.restaurantses = restaurantses;
	}

}
