package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Emails generated by hbm2java
 */
@Entity
@Table(name = "emails", catalog = "wollits")
public class Emails implements java.io.Serializable {

	private int emailId;
	private Contacts contacts;
	private String emailAddress;

	public Emails() {
	}

	public Emails(int emailId, String emailAddress) {
		this.emailId = emailId;
		this.emailAddress = emailAddress;
	}

	public Emails(int emailId, Contacts contacts, String emailAddress) {
		this.emailId = emailId;
		this.contacts = contacts;
		this.emailAddress = emailAddress;
	}

	@Id
	@Column(name = "email_id", unique = true, nullable = false)
	public int getEmailId() {
		return this.emailId;
	}

	public void setEmailId(int emailId) {
		this.emailId = emailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_id")
	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	@Column(name = "email_address", nullable = false)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

}
