package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FixedDeliveryRates generated by hbm2java
 */
@Entity
@Table(name = "fixed_delivery_rates", catalog = "wollits")
public class FixedDeliveryRates implements java.io.Serializable {

	private int fixedDeliveryRateId;
	private Restaurants restaurants;
	private double maximumDistanceKm;
	private byte[] price;

	public FixedDeliveryRates() {
	}

	public FixedDeliveryRates(int fixedDeliveryRateId, Restaurants restaurants,
			double maximumDistanceKm, byte[] price) {
		this.fixedDeliveryRateId = fixedDeliveryRateId;
		this.restaurants = restaurants;
		this.maximumDistanceKm = maximumDistanceKm;
		this.price = price;
	}

	@Id
	@Column(name = "fixed_delivery_rate_id", unique = true, nullable = false)
	public int getFixedDeliveryRateId() {
		return this.fixedDeliveryRateId;
	}

	public void setFixedDeliveryRateId(int fixedDeliveryRateId) {
		this.fixedDeliveryRateId = fixedDeliveryRateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurants getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Restaurants restaurants) {
		this.restaurants = restaurants;
	}

	@Column(name = "maximum_distance_km", nullable = false, precision = 22, scale = 0)
	public double getMaximumDistanceKm() {
		return this.maximumDistanceKm;
	}

	public void setMaximumDistanceKm(double maximumDistanceKm) {
		this.maximumDistanceKm = maximumDistanceKm;
	}

	@Column(name = "price", nullable = false)
	public byte[] getPrice() {
		return this.price;
	}

	public void setPrice(byte[] price) {
		this.price = price;
	}

}
