package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MenuItemCustomizations generated by hbm2java
 */
@Entity
@Table(name = "menu_item_customizations", catalog = "wollits")
public class MenuItemCustomizations implements java.io.Serializable {

	private int menuItemCustomizationsId;
	private Customizations customizations;
	private MenuItems menuItems;
	private Integer priority;

	public MenuItemCustomizations() {
	}

	public MenuItemCustomizations(int menuItemCustomizationsId) {
		this.menuItemCustomizationsId = menuItemCustomizationsId;
	}

	public MenuItemCustomizations(int menuItemCustomizationsId,
			Customizations customizations, MenuItems menuItems, Integer priority) {
		this.menuItemCustomizationsId = menuItemCustomizationsId;
		this.customizations = customizations;
		this.menuItems = menuItems;
		this.priority = priority;
	}

	@Id
	@Column(name = "menu_item_customizations_id", unique = true, nullable = false)
	public int getMenuItemCustomizationsId() {
		return this.menuItemCustomizationsId;
	}

	public void setMenuItemCustomizationsId(int menuItemCustomizationsId) {
		this.menuItemCustomizationsId = menuItemCustomizationsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customization_id")
	public Customizations getCustomizations() {
		return this.customizations;
	}

	public void setCustomizations(Customizations customizations) {
		this.customizations = customizations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_item_id")
	public MenuItems getMenuItems() {
		return this.menuItems;
	}

	public void setMenuItems(MenuItems menuItems) {
		this.menuItems = menuItems;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

}
