package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MenuItemSizePrices generated by hbm2java
 */
@Entity
@Table(name = "menu_item_size_prices", catalog = "wollits")
public class MenuItemSizePrices implements java.io.Serializable {

	private int menuItemSizePriceId;
	private Sizes sizes;
	private MenuItems menuItems;
	private byte[] price;
	private Integer priority;
	private Set<OrderMenuItems> orderMenuItemses = new HashSet<OrderMenuItems>(
			0);

	public MenuItemSizePrices() {
	}

	public MenuItemSizePrices(int menuItemSizePriceId, Sizes sizes,
			MenuItems menuItems) {
		this.menuItemSizePriceId = menuItemSizePriceId;
		this.sizes = sizes;
		this.menuItems = menuItems;
	}

	public MenuItemSizePrices(int menuItemSizePriceId, Sizes sizes,
			MenuItems menuItems, byte[] price, Integer priority,
			Set<OrderMenuItems> orderMenuItemses) {
		this.menuItemSizePriceId = menuItemSizePriceId;
		this.sizes = sizes;
		this.menuItems = menuItems;
		this.price = price;
		this.priority = priority;
		this.orderMenuItemses = orderMenuItemses;
	}

	@Id
	@Column(name = "menu_item_size_price_id", unique = true, nullable = false)
	public int getMenuItemSizePriceId() {
		return this.menuItemSizePriceId;
	}

	public void setMenuItemSizePriceId(int menuItemSizePriceId) {
		this.menuItemSizePriceId = menuItemSizePriceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "size_id", nullable = false)
	public Sizes getSizes() {
		return this.sizes;
	}

	public void setSizes(Sizes sizes) {
		this.sizes = sizes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_item_id", nullable = false)
	public MenuItems getMenuItems() {
		return this.menuItems;
	}

	public void setMenuItems(MenuItems menuItems) {
		this.menuItems = menuItems;
	}

	@Column(name = "price")
	public byte[] getPrice() {
		return this.price;
	}

	public void setPrice(byte[] price) {
		this.price = price;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuItemSizePrices")
	public Set<OrderMenuItems> getOrderMenuItemses() {
		return this.orderMenuItemses;
	}

	public void setOrderMenuItemses(Set<OrderMenuItems> orderMenuItemses) {
		this.orderMenuItemses = orderMenuItemses;
	}

}
