package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menus generated by hbm2java
 */
@Entity
@Table(name = "menus", catalog = "wollits")
public class Menus implements java.io.Serializable {

	private int menuId;
	private String name;
	private Integer priority;
	private Set<RestaurantMenus> restaurantMenuses = new HashSet<RestaurantMenus>(
			0);
	private Set<MenuSections> menuSectionses = new HashSet<MenuSections>(0);

	public Menus() {
	}

	public Menus(int menuId, String name) {
		this.menuId = menuId;
		this.name = name;
	}

	public Menus(int menuId, String name, Integer priority,
			Set<RestaurantMenus> restaurantMenuses,
			Set<MenuSections> menuSectionses) {
		this.menuId = menuId;
		this.name = name;
		this.priority = priority;
		this.restaurantMenuses = restaurantMenuses;
		this.menuSectionses = menuSectionses;
	}

	@Id
	@Column(name = "menu_id", unique = true, nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menus")
	public Set<RestaurantMenus> getRestaurantMenuses() {
		return this.restaurantMenuses;
	}

	public void setRestaurantMenuses(Set<RestaurantMenus> restaurantMenuses) {
		this.restaurantMenuses = restaurantMenuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menus")
	public Set<MenuSections> getMenuSectionses() {
		return this.menuSectionses;
	}

	public void setMenuSectionses(Set<MenuSections> menuSectionses) {
		this.menuSectionses = menuSectionses;
	}

}
