package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderMenuItems generated by hbm2java
 */
@Entity
@Table(name = "order_menu_items", catalog = "wollits")
public class OrderMenuItems implements java.io.Serializable {

	private int orderMenuItemId;
	private MenuItemSizePrices menuItemSizePrices;
	private Orders orders;
	private MenuItems menuItems;
	private int quantity;
	private Set<OrderMenuItemCustomizations> orderMenuItemCustomizationses = new HashSet<OrderMenuItemCustomizations>(
			0);

	public OrderMenuItems() {
	}

	public OrderMenuItems(int orderMenuItemId,
			MenuItemSizePrices menuItemSizePrices, Orders orders,
			MenuItems menuItems, int quantity) {
		this.orderMenuItemId = orderMenuItemId;
		this.menuItemSizePrices = menuItemSizePrices;
		this.orders = orders;
		this.menuItems = menuItems;
		this.quantity = quantity;
	}

	public OrderMenuItems(int orderMenuItemId,
			MenuItemSizePrices menuItemSizePrices, Orders orders,
			MenuItems menuItems, int quantity,
			Set<OrderMenuItemCustomizations> orderMenuItemCustomizationses) {
		this.orderMenuItemId = orderMenuItemId;
		this.menuItemSizePrices = menuItemSizePrices;
		this.orders = orders;
		this.menuItems = menuItems;
		this.quantity = quantity;
		this.orderMenuItemCustomizationses = orderMenuItemCustomizationses;
	}

	@Id
	@Column(name = "order_menu_item_id", unique = true, nullable = false)
	public int getOrderMenuItemId() {
		return this.orderMenuItemId;
	}

	public void setOrderMenuItemId(int orderMenuItemId) {
		this.orderMenuItemId = orderMenuItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_item_size_price_id", nullable = false)
	public MenuItemSizePrices getMenuItemSizePrices() {
		return this.menuItemSizePrices;
	}

	public void setMenuItemSizePrices(MenuItemSizePrices menuItemSizePrices) {
		this.menuItemSizePrices = menuItemSizePrices;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_item_id", nullable = false)
	public MenuItems getMenuItems() {
		return this.menuItems;
	}

	public void setMenuItems(MenuItems menuItems) {
		this.menuItems = menuItems;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderMenuItems")
	public Set<OrderMenuItemCustomizations> getOrderMenuItemCustomizationses() {
		return this.orderMenuItemCustomizationses;
	}

	public void setOrderMenuItemCustomizationses(
			Set<OrderMenuItemCustomizations> orderMenuItemCustomizationses) {
		this.orderMenuItemCustomizationses = orderMenuItemCustomizationses;
	}

}
