package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderSelectedCustomizationOptions generated by hbm2java
 */
@Entity
@Table(name = "order_selected_customization_options", catalog = "wollits")
public class OrderSelectedCustomizationOptions implements java.io.Serializable {

	private int orderCustomizationOptionId;
	private OrderCustomizations orderCustomizations;
	private CustomizationOptions customizationOptions;

	public OrderSelectedCustomizationOptions() {
	}

	public OrderSelectedCustomizationOptions(int orderCustomizationOptionId,
			OrderCustomizations orderCustomizations,
			CustomizationOptions customizationOptions) {
		this.orderCustomizationOptionId = orderCustomizationOptionId;
		this.orderCustomizations = orderCustomizations;
		this.customizationOptions = customizationOptions;
	}

	@Id
	@Column(name = "order_customization_option_id", unique = true, nullable = false)
	public int getOrderCustomizationOptionId() {
		return this.orderCustomizationOptionId;
	}

	public void setOrderCustomizationOptionId(int orderCustomizationOptionId) {
		this.orderCustomizationOptionId = orderCustomizationOptionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_customization_id", nullable = false)
	public OrderCustomizations getOrderCustomizations() {
		return this.orderCustomizations;
	}

	public void setOrderCustomizations(OrderCustomizations orderCustomizations) {
		this.orderCustomizations = orderCustomizations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customization_option_id", nullable = false)
	public CustomizationOptions getCustomizationOptions() {
		return this.customizationOptions;
	}

	public void setCustomizationOptions(
			CustomizationOptions customizationOptions) {
		this.customizationOptions = customizationOptions;
	}

}
