package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderCustomizations generated by hbm2java
 */
@Entity
@Table(name = "order_customizations", catalog = "wollits")
public class OrderCustomizations implements java.io.Serializable {

	private int orderCustomizationId;
	private Customizations customizations;
	private Set<OrderMenuItemCustomizations> orderMenuItemCustomizationses = new HashSet<OrderMenuItemCustomizations>(
			0);
	private Set<OrderSelectedCustomizationOptions> orderSelectedCustomizationOptionses = new HashSet<OrderSelectedCustomizationOptions>(
			0);

	public OrderCustomizations() {
	}

	public OrderCustomizations(int orderCustomizationId,
			Customizations customizations) {
		this.orderCustomizationId = orderCustomizationId;
		this.customizations = customizations;
	}

	public OrderCustomizations(
			int orderCustomizationId,
			Customizations customizations,
			Set<OrderMenuItemCustomizations> orderMenuItemCustomizationses,
			Set<OrderSelectedCustomizationOptions> orderSelectedCustomizationOptionses) {
		this.orderCustomizationId = orderCustomizationId;
		this.customizations = customizations;
		this.orderMenuItemCustomizationses = orderMenuItemCustomizationses;
		this.orderSelectedCustomizationOptionses = orderSelectedCustomizationOptionses;
	}

	@Id
	@Column(name = "order_customization_id", unique = true, nullable = false)
	public int getOrderCustomizationId() {
		return this.orderCustomizationId;
	}

	public void setOrderCustomizationId(int orderCustomizationId) {
		this.orderCustomizationId = orderCustomizationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customization_id", nullable = false)
	public Customizations getCustomizations() {
		return this.customizations;
	}

	public void setCustomizations(Customizations customizations) {
		this.customizations = customizations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderCustomizations")
	public Set<OrderMenuItemCustomizations> getOrderMenuItemCustomizationses() {
		return this.orderMenuItemCustomizationses;
	}

	public void setOrderMenuItemCustomizationses(
			Set<OrderMenuItemCustomizations> orderMenuItemCustomizationses) {
		this.orderMenuItemCustomizationses = orderMenuItemCustomizationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderCustomizations")
	public Set<OrderSelectedCustomizationOptions> getOrderSelectedCustomizationOptionses() {
		return this.orderSelectedCustomizationOptionses;
	}

	public void setOrderSelectedCustomizationOptionses(
			Set<OrderSelectedCustomizationOptions> orderSelectedCustomizationOptionses) {
		this.orderSelectedCustomizationOptionses = orderSelectedCustomizationOptionses;
	}

}
