package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderMenuItemCustomizations generated by hbm2java
 */
@Entity
@Table(name = "order_menu_item_customizations", catalog = "wollits")
public class OrderMenuItemCustomizations implements java.io.Serializable {

	private int orderMenuItemCustomizationId;
	private OrderCustomizations orderCustomizations;
	private OrderMenuItems orderMenuItems;

	public OrderMenuItemCustomizations() {
	}

	public OrderMenuItemCustomizations(int orderMenuItemCustomizationId,
			OrderCustomizations orderCustomizations,
			OrderMenuItems orderMenuItems) {
		this.orderMenuItemCustomizationId = orderMenuItemCustomizationId;
		this.orderCustomizations = orderCustomizations;
		this.orderMenuItems = orderMenuItems;
	}

	@Id
	@Column(name = "order_menu_item_customization_id", unique = true, nullable = false)
	public int getOrderMenuItemCustomizationId() {
		return this.orderMenuItemCustomizationId;
	}

	public void setOrderMenuItemCustomizationId(int orderMenuItemCustomizationId) {
		this.orderMenuItemCustomizationId = orderMenuItemCustomizationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_customization_id", nullable = false)
	public OrderCustomizations getOrderCustomizations() {
		return this.orderCustomizations;
	}

	public void setOrderCustomizations(OrderCustomizations orderCustomizations) {
		this.orderCustomizations = orderCustomizations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_menu_item_id", nullable = false)
	public OrderMenuItems getOrderMenuItems() {
		return this.orderMenuItems;
	}

	public void setOrderMenuItems(OrderMenuItems orderMenuItems) {
		this.orderMenuItems = orderMenuItems;
	}

}
