package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RestaurantRoles generated by hbm2java
 */
@Entity
@Table(name = "restaurant_roles", catalog = "wollits")
public class RestaurantRoles implements java.io.Serializable {

	private int restaurantRoleId;
	private Roles roles;
	private Restaurants restaurants;
	private Set<UserRestaurantRoles> userRestaurantRoleses = new HashSet<UserRestaurantRoles>(
			0);

	public RestaurantRoles() {
	}

	public RestaurantRoles(int restaurantRoleId, Roles roles,
			Restaurants restaurants) {
		this.restaurantRoleId = restaurantRoleId;
		this.roles = roles;
		this.restaurants = restaurants;
	}

	public RestaurantRoles(int restaurantRoleId, Roles roles,
			Restaurants restaurants,
			Set<UserRestaurantRoles> userRestaurantRoleses) {
		this.restaurantRoleId = restaurantRoleId;
		this.roles = roles;
		this.restaurants = restaurants;
		this.userRestaurantRoleses = userRestaurantRoleses;
	}

	@Id
	@Column(name = "restaurant_role_id", unique = true, nullable = false)
	public int getRestaurantRoleId() {
		return this.restaurantRoleId;
	}

	public void setRestaurantRoleId(int restaurantRoleId) {
		this.restaurantRoleId = restaurantRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurants getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Restaurants restaurants) {
		this.restaurants = restaurants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurantRoles")
	public Set<UserRestaurantRoles> getUserRestaurantRoleses() {
		return this.userRestaurantRoleses;
	}

	public void setUserRestaurantRoleses(
			Set<UserRestaurantRoles> userRestaurantRoleses) {
		this.userRestaurantRoleses = userRestaurantRoleses;
	}

}
