package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "wollits")
public class Roles implements java.io.Serializable {

	private int roleId;
	private String name;
	private Set<RestaurantRoles> restaurantRoleses = new HashSet<RestaurantRoles>(
			0);

	public Roles() {
		
	}

	public Roles(int roleId, String name) {
		this.roleId = roleId;
		this.name = name;
	}

	public Roles(int roleId, String name, Set<RestaurantRoles> restaurantRoleses) {
		this.roleId = roleId;
		this.name = name;
		this.restaurantRoleses = restaurantRoleses;
	}

	@Id
	@Column(name = "role_id", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<RestaurantRoles> getRestaurantRoleses() {
		return this.restaurantRoleses;
	}

	public void setRestaurantRoleses(Set<RestaurantRoles> restaurantRoleses) {
		this.restaurantRoleses = restaurantRoleses;
	}

}
