package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ServiceTypes generated by hbm2java
 */
@Entity
@Table(name = "service_types", catalog = "wollits")
public class ServiceTypes implements java.io.Serializable {

	private int serviceTypeId;
	private String name;
	private String comment;

	public ServiceTypes() {
	}

	public ServiceTypes(int serviceTypeId, String name) {
		this.serviceTypeId = serviceTypeId;
		this.name = name;
	}

	public ServiceTypes(int serviceTypeId, String name, String comment) {
		this.serviceTypeId = serviceTypeId;
		this.name = name;
		this.comment = comment;
	}

	@Id
	@Column(name = "service_type_id", unique = true, nullable = false)
	public int getServiceTypeId() {
		return this.serviceTypeId;
	}

	public void setServiceTypeId(int serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
