package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sizes generated by hbm2java
 */
@Entity
@Table(name = "sizes", catalog = "wollits")
public class Sizes implements java.io.Serializable {

	private int sizeId;
	private String name;
	private Set<MenuItemSizePrices> menuItemSizePriceses = new HashSet<MenuItemSizePrices>(
			0);

	public Sizes() {
	}

	public Sizes(int sizeId) {
		this.sizeId = sizeId;
	}

	public Sizes(int sizeId, String name,
			Set<MenuItemSizePrices> menuItemSizePriceses) {
		this.sizeId = sizeId;
		this.name = name;
		this.menuItemSizePriceses = menuItemSizePriceses;
	}

	@Id
	@Column(name = "size_id", unique = true, nullable = false)
	public int getSizeId() {
		return this.sizeId;
	}

	public void setSizeId(int sizeId) {
		this.sizeId = sizeId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sizes")
	public Set<MenuItemSizePrices> getMenuItemSizePriceses() {
		return this.menuItemSizePriceses;
	}

	public void setMenuItemSizePriceses(
			Set<MenuItemSizePrices> menuItemSizePriceses) {
		this.menuItemSizePriceses = menuItemSizePriceses;
	}

}
