package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRestaurantRoles generated by hbm2java
 */
@Entity
@Table(name = "user_restaurant_roles", catalog = "wollits")
public class UserRestaurantRoles implements java.io.Serializable {

	private int userRestaurantRoleId;
	private RestaurantRoles restaurantRoles;
	private int userId;

	public UserRestaurantRoles() {
	}

	public UserRestaurantRoles(int userRestaurantRoleId,
			RestaurantRoles restaurantRoles, int userId) {
		this.userRestaurantRoleId = userRestaurantRoleId;
		this.restaurantRoles = restaurantRoles;
		this.userId = userId;
	}

	@Id
	@Column(name = "user_restaurant_role_id", unique = true, nullable = false)
	public int getUserRestaurantRoleId() {
		return this.userRestaurantRoleId;
	}

	public void setUserRestaurantRoleId(int userRestaurantRoleId) {
		this.userRestaurantRoleId = userRestaurantRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_role_id", nullable = false)
	public RestaurantRoles getRestaurantRoles() {
		return this.restaurantRoles;
	}

	public void setRestaurantRoles(RestaurantRoles restaurantRoles) {
		this.restaurantRoles = restaurantRoles;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
