package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contacts generated by hbm2java
 */
@Entity
@Table(name = "contacts", catalog = "wollits")
public class Contacts implements java.io.Serializable {

	private int contactId;
	private int userId;
	private String name;
	private String description;
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<Phones> phoneses = new HashSet<Phones>(0);
	private Set<Emails> emailses = new HashSet<Emails>(0);

	public Contacts() {
	}

	public Contacts(int contactId, int userId, String name) {
		this.contactId = contactId;
		this.userId = userId;
		this.name = name;
	}

	public Contacts(int contactId, int userId, String name, String description,
			Set<Orders> orderses, Set<Phones> phoneses, Set<Emails> emailses) {
		this.contactId = contactId;
		this.userId = userId;
		this.name = name;
		this.description = description;
		this.orderses = orderses;
		this.phoneses = phoneses;
		this.emailses = emailses;
	}

	@Id
	@Column(name = "contact_id", unique = true, nullable = false)
	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contacts")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contacts")
	public Set<Phones> getPhoneses() {
		return this.phoneses;
	}

	public void setPhoneses(Set<Phones> phoneses) {
		this.phoneses = phoneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contacts")
	public Set<Emails> getEmailses() {
		return this.emailses;
	}

	public void setEmailses(Set<Emails> emailses) {
		this.emailses = emailses;
	}

}
