package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "countries", catalog = "wollits")
public class Countries implements java.io.Serializable {

	private int countryId;
	private String name;
	private String isoAlpha2;
	private int countryCode;
	private Set<States> stateses = new HashSet<States>(0);

	public Countries() {
	}

	public Countries(int countryId, String name, String isoAlpha2,
			int countryCode) {
		this.countryId = countryId;
		this.name = name;
		this.isoAlpha2 = isoAlpha2;
		this.countryCode = countryCode;
	}

	public Countries(int countryId, String name, String isoAlpha2,
			int countryCode, Set<States> stateses) {
		this.countryId = countryId;
		this.name = name;
		this.isoAlpha2 = isoAlpha2;
		this.countryCode = countryCode;
		this.stateses = stateses;
	}

	@Id
	@Column(name = "country_id", unique = true, nullable = false)
	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "iso_alpha_2", nullable = false)
	public String getIsoAlpha2() {
		return this.isoAlpha2;
	}

	public void setIsoAlpha2(String isoAlpha2) {
		this.isoAlpha2 = isoAlpha2;
	}

	@Column(name = "country_code", nullable = false)
	public int getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(int countryCode) {
		this.countryCode = countryCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countries")
	public Set<States> getStateses() {
		return this.stateses;
	}

	public void setStateses(Set<States> stateses) {
		this.stateses = stateses;
	}

}
