package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customizations generated by hbm2java
 */
@Entity
@Table(name = "customizations", catalog = "wollits")
public class Customizations implements java.io.Serializable {

	private int customizationId;
	private String name;
	private String type;
	private String description;
	private Set<OrderCustomizations> orderCustomizationses = new HashSet<OrderCustomizations>(
			0);
	private Set<CustomizationOptions> customizationOptionses = new HashSet<CustomizationOptions>(
			0);
	private Set<MenuItemCustomizations> menuItemCustomizationses = new HashSet<MenuItemCustomizations>(
			0);

	public Customizations() {
	}

	public Customizations(int customizationId, String name, String type) {
		this.customizationId = customizationId;
		this.name = name;
		this.type = type;
	}

	public Customizations(int customizationId, String name, String type,
			String description, Set<OrderCustomizations> orderCustomizationses,
			Set<CustomizationOptions> customizationOptionses,
			Set<MenuItemCustomizations> menuItemCustomizationses) {
		this.customizationId = customizationId;
		this.name = name;
		this.type = type;
		this.description = description;
		this.orderCustomizationses = orderCustomizationses;
		this.customizationOptionses = customizationOptionses;
		this.menuItemCustomizationses = menuItemCustomizationses;
	}

	@Id
	@Column(name = "customization_id", unique = true, nullable = false)
	public int getCustomizationId() {
		return this.customizationId;
	}

	public void setCustomizationId(int customizationId) {
		this.customizationId = customizationId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customizations")
	public Set<OrderCustomizations> getOrderCustomizationses() {
		return this.orderCustomizationses;
	}

	public void setOrderCustomizationses(
			Set<OrderCustomizations> orderCustomizationses) {
		this.orderCustomizationses = orderCustomizationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customizations")
	public Set<CustomizationOptions> getCustomizationOptionses() {
		return this.customizationOptionses;
	}

	public void setCustomizationOptionses(
			Set<CustomizationOptions> customizationOptionses) {
		this.customizationOptionses = customizationOptionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customizations")
	public Set<MenuItemCustomizations> getMenuItemCustomizationses() {
		return this.menuItemCustomizationses;
	}

	public void setMenuItemCustomizationses(
			Set<MenuItemCustomizations> menuItemCustomizationses) {
		this.menuItemCustomizationses = menuItemCustomizationses;
	}

}
