package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MenuSections generated by hbm2java
 */
@Entity
@Table(name = "menu_sections", catalog = "wollits")
public class MenuSections implements java.io.Serializable {

	private int menuSectionId;
	private Menus menus;
	private String name;
	private String description;
	private Integer priority;
	private Set<MenuItems> menuItemses = new HashSet<MenuItems>(0);

	public MenuSections() {
	}

	public MenuSections(int menuSectionId, Menus menus, String name) {
		this.menuSectionId = menuSectionId;
		this.menus = menus;
		this.name = name;
	}

	public MenuSections(int menuSectionId, Menus menus, String name,
			String description, Integer priority, Set<MenuItems> menuItemses) {
		this.menuSectionId = menuSectionId;
		this.menus = menus;
		this.name = name;
		this.description = description;
		this.priority = priority;
		this.menuItemses = menuItemses;
	}

	@Id
	@Column(name = "menu_section_id", unique = true, nullable = false)
	public int getMenuSectionId() {
		return this.menuSectionId;
	}

	public void setMenuSectionId(int menuSectionId) {
		this.menuSectionId = menuSectionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id", nullable = false)
	public Menus getMenus() {
		return this.menus;
	}

	public void setMenus(Menus menus) {
		this.menus = menus;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuSections")
	public Set<MenuItems> getMenuItemses() {
		return this.menuItemses;
	}

	public void setMenuItemses(Set<MenuItems> menuItemses) {
		this.menuItemses = menuItemses;
	}

}
