package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MenuItems generated by hbm2java
 */
@Entity
@Table(name = "menu_items", catalog = "wollits")
public class MenuItems implements java.io.Serializable {

	private int menuItemId;
	private MenuSections menuSections;
	private String name;
	private String description;
	private String imageUrl;
	private String imageThumbUrl;
	private Integer priority;
	private Set<MenuItemSizePrices> menuItemSizePriceses = new HashSet<MenuItemSizePrices>(
			0);
	private Set<MenuItemCustomizations> menuItemCustomizationses = new HashSet<MenuItemCustomizations>(
			0);
	private Set<OrderMenuItems> orderMenuItemses = new HashSet<OrderMenuItems>(
			0);

	public MenuItems() {
	}

	public MenuItems(int menuItemId, String name) {
		this.menuItemId = menuItemId;
		this.name = name;
	}

	public MenuItems(int menuItemId, MenuSections menuSections, String name,
			String description, String imageUrl, String imageThumbUrl,
			Integer priority, Set<MenuItemSizePrices> menuItemSizePriceses,
			Set<MenuItemCustomizations> menuItemCustomizationses,
			Set<OrderMenuItems> orderMenuItemses) {
		this.menuItemId = menuItemId;
		this.menuSections = menuSections;
		this.name = name;
		this.description = description;
		this.imageUrl = imageUrl;
		this.imageThumbUrl = imageThumbUrl;
		this.priority = priority;
		this.menuItemSizePriceses = menuItemSizePriceses;
		this.menuItemCustomizationses = menuItemCustomizationses;
		this.orderMenuItemses = orderMenuItemses;
	}

	@Id
	@Column(name = "menu_item_id", unique = true, nullable = false)
	public int getMenuItemId() {
		return this.menuItemId;
	}

	public void setMenuItemId(int menuItemId) {
		this.menuItemId = menuItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_section_id")
	public MenuSections getMenuSections() {
		return this.menuSections;
	}

	public void setMenuSections(MenuSections menuSections) {
		this.menuSections = menuSections;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "image_thumb_url")
	public String getImageThumbUrl() {
		return this.imageThumbUrl;
	}

	public void setImageThumbUrl(String imageThumbUrl) {
		this.imageThumbUrl = imageThumbUrl;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuItems")
	public Set<MenuItemSizePrices> getMenuItemSizePriceses() {
		return this.menuItemSizePriceses;
	}

	public void setMenuItemSizePriceses(
			Set<MenuItemSizePrices> menuItemSizePriceses) {
		this.menuItemSizePriceses = menuItemSizePriceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuItems")
	public Set<MenuItemCustomizations> getMenuItemCustomizationses() {
		return this.menuItemCustomizationses;
	}

	public void setMenuItemCustomizationses(
			Set<MenuItemCustomizations> menuItemCustomizationses) {
		this.menuItemCustomizationses = menuItemCustomizationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuItems")
	public Set<OrderMenuItems> getOrderMenuItemses() {
		return this.orderMenuItemses;
	}

	public void setOrderMenuItemses(Set<OrderMenuItems> orderMenuItemses) {
		this.orderMenuItemses = orderMenuItemses;
	}

}
