package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PostCodes generated by hbm2java
 */
@Entity
@Table(name = "post_codes", catalog = "wollits")
public class PostCodes implements java.io.Serializable {

	private int postCodeId;
	private States states;
	private String postCode;
	private String city;
	private double latitude;
	private double longitude;
	private Set<Locations> locationses = new HashSet<Locations>(0);

	public PostCodes() {
	}

	public PostCodes(int postCodeId, States states, String postCode,
			String city, double latitude, double longitude) {
		this.postCodeId = postCodeId;
		this.states = states;
		this.postCode = postCode;
		this.city = city;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public PostCodes(int postCodeId, States states, String postCode,
			String city, double latitude, double longitude,
			Set<Locations> locationses) {
		this.postCodeId = postCodeId;
		this.states = states;
		this.postCode = postCode;
		this.city = city;
		this.latitude = latitude;
		this.longitude = longitude;
		this.locationses = locationses;
	}

	@Id
	@Column(name = "post_code_id", unique = true, nullable = false)
	public int getPostCodeId() {
		return this.postCodeId;
	}

	public void setPostCodeId(int postCodeId) {
		this.postCodeId = postCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "state_id", nullable = false)
	public States getStates() {
		return this.states;
	}

	public void setStates(States states) {
		this.states = states;
	}

	@Column(name = "post_code", nullable = false)
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	@Column(name = "city", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "latitude", nullable = false, precision = 22, scale = 0)
	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 22, scale = 0)
	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postCodes")
	public Set<Locations> getLocationses() {
		return this.locationses;
	}

	public void setLocationses(Set<Locations> locationses) {
		this.locationses = locationses;
	}

}
