package wollits.hibernate;

// Generated Jun 14, 2014 7:45:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserLocations generated by hbm2java
 */
@Entity
@Table(name = "user_locations", catalog = "wollits")
public class UserLocations implements java.io.Serializable {

	private int userLocationId;
	private Locations locations;
	private int userId;

	public UserLocations() {
	}

	public UserLocations(int userLocationId, Locations locations, int userId) {
		this.userLocationId = userLocationId;
		this.locations = locations;
		this.userId = userId;
	}

	@Id
	@Column(name = "user_location_id", unique = true, nullable = false)
	public int getUserLocationId() {
		return this.userLocationId;
	}

	public void setUserLocationId(int userLocationId) {
		this.userLocationId = userLocationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id", nullable = false)
	public Locations getLocations() {
		return this.locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
