package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer addressId;
	private Zone zone;
	private String streetAddress;
	private String unitNumber;
	private Set residences = new HashSet(0);
	private Set creditCardInfos = new HashSet(0);
	private Set restaurants = new HashSet(0);

	public Address() {
	}

	public Address(Zone zone, String streetAddress, String unitNumber,
			Set residences, Set creditCardInfos, Set restaurants) {
		this.zone = zone;
		this.streetAddress = streetAddress;
		this.unitNumber = unitNumber;
		this.residences = residences;
		this.creditCardInfos = creditCardInfos;
		this.restaurants = restaurants;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public Zone getZone() {
		return this.zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getUnitNumber() {
		return this.unitNumber;
	}

	public void setUnitNumber(String unitNumber) {
		this.unitNumber = unitNumber;
	}

	public Set getResidences() {
		return this.residences;
	}

	public void setResidences(Set residences) {
		this.residences = residences;
	}

	public Set getCreditCardInfos() {
		return this.creditCardInfos;
	}

	public void setCreditCardInfos(Set creditCardInfos) {
		this.creditCardInfos = creditCardInfos;
	}

	public Set getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set restaurants) {
		this.restaurants = restaurants;
	}

}
