package com.posbravo.model;
// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Authentication generated by hbm2java
 */
public class Authentication  implements java.io.Serializable {


     private Integer authenticationId;
     private User user;
     private String userName;
     private String password;
     private Integer pin;
     private boolean isEnabled;
     private Set authenticationLogs = new HashSet(0);

    public Authentication() {
    }

	
    public Authentication(User user, String userName, String password, boolean isEnabled) {
        this.user = user;
        this.userName = userName;
        this.password = password;
        this.isEnabled = isEnabled;
    }
    public Authentication(User user, String userName, String password, Integer pin, boolean isEnabled, Set authenticationLogs) {
       this.user = user;
       this.userName = userName;
       this.password = password;
       this.pin = pin;
       this.isEnabled = isEnabled;
       this.authenticationLogs = authenticationLogs;
    }
   
    public Integer getAuthenticationId() {
        return this.authenticationId;
    }
    
    public void setAuthenticationId(Integer authenticationId) {
        this.authenticationId = authenticationId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getPin() {
        return this.pin;
    }
    
    public void setPin(Integer pin) {
        this.pin = pin;
    }
    public boolean isIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(boolean isEnabled) {
        this.isEnabled = isEnabled;
    }
    public Set getAuthenticationLogs() {
        return this.authenticationLogs;
    }
    
    public void setAuthenticationLogs(Set authenticationLogs) {
        this.authenticationLogs = authenticationLogs;
    }




}


