package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer menuId;
	private String description;
	private String name;
	private Date startTime;
	private Date endTime;
	private Set restaurantMenus = new HashSet(0);
	private Set menuClassifications = new HashSet(0);

	public Menu() {
	}

	public Menu(String name, Date startTime, Date endTime) {
		this.name = name;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public Menu(String description, String name, Date startTime, Date endTime,
			Set restaurantMenus, Set menuClassifications) {
		this.description = description;
		this.name = name;
		this.startTime = startTime;
		this.endTime = endTime;
		this.restaurantMenus = restaurantMenus;
		this.menuClassifications = menuClassifications;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Set getRestaurantMenus() {
		return this.restaurantMenus;
	}

	public void setRestaurantMenus(Set restaurantMenus) {
		this.restaurantMenus = restaurantMenus;
	}

	public Set getMenuClassifications() {
		return this.menuClassifications;
	}

	public void setMenuClassifications(Set menuClassifications) {
		this.menuClassifications = menuClassifications;
	}

}
