package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * MenuClassification generated by hbm2java
 */
public class MenuClassification implements java.io.Serializable {

	private Integer menuClassificationId;
	private Menu menu;
	private Product product;
	private String type;

	public MenuClassification() {
	}

	public MenuClassification(Menu menu, Product product, String type) {
		this.menu = menu;
		this.product = product;
		this.type = type;
	}

	public Integer getMenuClassificationId() {
		return this.menuClassificationId;
	}

	public void setMenuClassificationId(Integer menuClassificationId) {
		this.menuClassificationId = menuClassificationId;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
