package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductCustomization generated by hbm2java
 */
public class ProductCustomization implements java.io.Serializable {

	private Integer productCustomizationId;
	private String description;
	private BigDecimal price;
	private Set productCustomizationToGroups = new HashSet(0);
	private Set cartItemCustomizations = new HashSet(0);

	public ProductCustomization() {
	}

	public ProductCustomization(BigDecimal price) {
		this.price = price;
	}

	public ProductCustomization(String description, BigDecimal price,
			Set productCustomizationToGroups, Set cartItemCustomizations) {
		this.description = description;
		this.price = price;
		this.productCustomizationToGroups = productCustomizationToGroups;
		this.cartItemCustomizations = cartItemCustomizations;
	}

	public Integer getProductCustomizationId() {
		return this.productCustomizationId;
	}

	public void setProductCustomizationId(Integer productCustomizationId) {
		this.productCustomizationId = productCustomizationId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Set getProductCustomizationToGroups() {
		return this.productCustomizationToGroups;
	}

	public void setProductCustomizationToGroups(Set productCustomizationToGroups) {
		this.productCustomizationToGroups = productCustomizationToGroups;
	}

	public Set getCartItemCustomizations() {
		return this.cartItemCustomizations;
	}

	public void setCartItemCustomizations(Set cartItemCustomizations) {
		this.cartItemCustomizations = cartItemCustomizations;
	}

}
