package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProductTagToProduct generated by hbm2java
 */
public class ProductTagToProduct implements java.io.Serializable {

	private Integer productTagToProductId;
	private Product product;
	private ProductTag productTag;

	public ProductTagToProduct() {
	}

	public ProductTagToProduct(Product product, ProductTag productTag) {
		this.product = product;
		this.productTag = productTag;
	}

	public Integer getProductTagToProductId() {
		return this.productTagToProductId;
	}

	public void setProductTagToProductId(Integer productTagToProductId) {
		this.productTagToProductId = productTagToProductId;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public ProductTag getProductTag() {
		return this.productTag;
	}

	public void setProductTag(ProductTag productTag) {
		this.productTag = productTag;
	}

}
