package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductCustomizationGroup generated by hbm2java
 */
public class ProductCustomizationGroup implements java.io.Serializable {

	private Integer productCustomizationGroupId;
	private String name;
	private boolean multipleSelection;
	private Set products = new HashSet(0);
	private Set productCustomizationToGroups = new HashSet(0);

	public ProductCustomizationGroup() {
	}

	public ProductCustomizationGroup(String name, boolean multipleSelection) {
		this.name = name;
		this.multipleSelection = multipleSelection;
	}

	public ProductCustomizationGroup(String name, boolean multipleSelection,
			Set products, Set productCustomizationToGroups) {
		this.name = name;
		this.multipleSelection = multipleSelection;
		this.products = products;
		this.productCustomizationToGroups = productCustomizationToGroups;
	}

	public Integer getProductCustomizationGroupId() {
		return this.productCustomizationGroupId;
	}

	public void setProductCustomizationGroupId(
			Integer productCustomizationGroupId) {
		this.productCustomizationGroupId = productCustomizationGroupId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isMultipleSelection() {
		return this.multipleSelection;
	}

	public void setMultipleSelection(boolean multipleSelection) {
		this.multipleSelection = multipleSelection;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

	public Set getProductCustomizationToGroups() {
		return this.productCustomizationToGroups;
	}

	public void setProductCustomizationToGroups(Set productCustomizationToGroups) {
		this.productCustomizationToGroups = productCustomizationToGroups;
	}

}
