package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PromotionUsage generated by hbm2java
 */
public class PromotionUsage implements java.io.Serializable {

	private Integer promotionUsageId;
	private Promotion promotion;
	private PromotionGroup promotionGroup;
	private User user;
	private Date dateUsed;

	public PromotionUsage() {
	}

	public PromotionUsage(Promotion promotion, User user, Date dateUsed) {
		this.promotion = promotion;
		this.user = user;
		this.dateUsed = dateUsed;
	}

	public PromotionUsage(Promotion promotion, PromotionGroup promotionGroup,
			User user, Date dateUsed) {
		this.promotion = promotion;
		this.promotionGroup = promotionGroup;
		this.user = user;
		this.dateUsed = dateUsed;
	}

	public Integer getPromotionUsageId() {
		return this.promotionUsageId;
	}

	public void setPromotionUsageId(Integer promotionUsageId) {
		this.promotionUsageId = promotionUsageId;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public PromotionGroup getPromotionGroup() {
		return this.promotionGroup;
	}

	public void setPromotionGroup(PromotionGroup promotionGroup) {
		this.promotionGroup = promotionGroup;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDateUsed() {
		return this.dateUsed;
	}

	public void setDateUsed(Date dateUsed) {
		this.dateUsed = dateUsed;
	}

}
