package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * PromotionToPromotionGroup generated by hbm2java
 */
public class PromotionToPromotionGroup implements java.io.Serializable {

	private Integer promotionToPromotionGroupId;
	private Promotion promotion;
	private PromotionGroup promotionGroup;

	public PromotionToPromotionGroup() {
	}

	public PromotionToPromotionGroup(Promotion promotion,
			PromotionGroup promotionGroup) {
		this.promotion = promotion;
		this.promotionGroup = promotionGroup;
	}

	public Integer getPromotionToPromotionGroupId() {
		return this.promotionToPromotionGroupId;
	}

	public void setPromotionToPromotionGroupId(
			Integer promotionToPromotionGroupId) {
		this.promotionToPromotionGroupId = promotionToPromotionGroupId;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public PromotionGroup getPromotionGroup() {
		return this.promotionGroup;
	}

	public void setPromotionGroup(PromotionGroup promotionGroup) {
		this.promotionGroup = promotionGroup;
	}

}
