package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Rates generated by hbm2java
 */
public class Rates implements java.io.Serializable {

	private Integer ratesId;
	private BigDecimal hourlyRate;
	private BigDecimal overTimeRate;
	private BigDecimal flatRate;
	private Set labors = new HashSet(0);

	public Rates() {
	}

	public Rates(BigDecimal hourlyRate, BigDecimal overTimeRate,
			BigDecimal flatRate, Set labors) {
		this.hourlyRate = hourlyRate;
		this.overTimeRate = overTimeRate;
		this.flatRate = flatRate;
		this.labors = labors;
	}

	public Integer getRatesId() {
		return this.ratesId;
	}

	public void setRatesId(Integer ratesId) {
		this.ratesId = ratesId;
	}

	public BigDecimal getHourlyRate() {
		return this.hourlyRate;
	}

	public void setHourlyRate(BigDecimal hourlyRate) {
		this.hourlyRate = hourlyRate;
	}

	public BigDecimal getOverTimeRate() {
		return this.overTimeRate;
	}

	public void setOverTimeRate(BigDecimal overTimeRate) {
		this.overTimeRate = overTimeRate;
	}

	public BigDecimal getFlatRate() {
		return this.flatRate;
	}

	public void setFlatRate(BigDecimal flatRate) {
		this.flatRate = flatRate;
	}

	public Set getLabors() {
		return this.labors;
	}

	public void setLabors(Set labors) {
		this.labors = labors;
	}

}
