package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant implements java.io.Serializable {

	private Integer restaurantId;
	private Address address;
	private String name;
	private String branch;
	private String description;
	private Date dateCreated;
	private Date dateModified;
	private Set userRestaurants = new HashSet(0);
	private Set restaurantPromotions = new HashSet(0);
	private Set restaurantMenus = new HashSet(0);

	public Restaurant() {
	}

	public Restaurant(Date dateCreated, Date dateModified) {
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	public Restaurant(Address address, String name, String branch,
			String description, Date dateCreated, Date dateModified,
			Set userRestaurants, Set restaurantPromotions, Set restaurantMenus) {
		this.address = address;
		this.name = name;
		this.branch = branch;
		this.description = description;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.userRestaurants = userRestaurants;
		this.restaurantPromotions = restaurantPromotions;
		this.restaurantMenus = restaurantMenus;
	}

	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(Integer restaurantId) {
		this.restaurantId = restaurantId;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public Set getUserRestaurants() {
		return this.userRestaurants;
	}

	public void setUserRestaurants(Set userRestaurants) {
		this.userRestaurants = userRestaurants;
	}

	public Set getRestaurantPromotions() {
		return this.restaurantPromotions;
	}

	public void setRestaurantPromotions(Set restaurantPromotions) {
		this.restaurantPromotions = restaurantPromotions;
	}

	public Set getRestaurantMenus() {
		return this.restaurantMenus;
	}

	public void setRestaurantMenus(Set restaurantMenus) {
		this.restaurantMenus = restaurantMenus;
	}

}
