package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * SecurityQuestion generated by hbm2java
 */
public class SecurityQuestion implements java.io.Serializable {

	private Integer securityQuestionId;
	private User user;
	private String question;
	private String answer;

	public SecurityQuestion() {
	}

	public SecurityQuestion(User user, String question, String answer) {
		this.user = user;
		this.question = question;
		this.answer = answer;
	}

	public Integer getSecurityQuestionId() {
		return this.securityQuestionId;
	}

	public void setSecurityQuestionId(Integer securityQuestionId) {
		this.securityQuestionId = securityQuestionId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
