package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Shipping generated by hbm2java
 */
public class Shipping implements java.io.Serializable {

	private Integer shippingId;
	private ShippingClass shippingClass;
	private BigDecimal rate;
	private String type;
	private Date dateLastModified;
	private Date dateAdded;

	public Shipping() {
	}

	public Shipping(ShippingClass shippingClass, BigDecimal rate,
			Date dateLastModified, Date dateAdded) {
		this.shippingClass = shippingClass;
		this.rate = rate;
		this.dateLastModified = dateLastModified;
		this.dateAdded = dateAdded;
	}

	public Shipping(ShippingClass shippingClass, BigDecimal rate, String type,
			Date dateLastModified, Date dateAdded) {
		this.shippingClass = shippingClass;
		this.rate = rate;
		this.type = type;
		this.dateLastModified = dateLastModified;
		this.dateAdded = dateAdded;
	}

	public Integer getShippingId() {
		return this.shippingId;
	}

	public void setShippingId(Integer shippingId) {
		this.shippingId = shippingId;
	}

	public ShippingClass getShippingClass() {
		return this.shippingClass;
	}

	public void setShippingClass(ShippingClass shippingClass) {
		this.shippingClass = shippingClass;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getDateLastModified() {
		return this.dateLastModified;
	}

	public void setDateLastModified(Date dateLastModified) {
		this.dateLastModified = dateLastModified;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
