package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Zone generated by hbm2java
 */
public class Zone implements java.io.Serializable {

	private Integer zoneId;
	private String zip;
	private String zipPlusFour;
	private String state;
	private String city;
	private Set addresses = new HashSet(0);
	private Set deliveries = new HashSet(0);

	public Zone() {
	}

	public Zone(String zip, String zipPlusFour, String state, String city,
			Set addresses, Set deliveries) {
		this.zip = zip;
		this.zipPlusFour = zipPlusFour;
		this.state = state;
		this.city = city;
		this.addresses = addresses;
		this.deliveries = deliveries;
	}

	public Integer getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(Integer zoneId) {
		this.zoneId = zoneId;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getZipPlusFour() {
		return this.zipPlusFour;
	}

	public void setZipPlusFour(String zipPlusFour) {
		this.zipPlusFour = zipPlusFour;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

	public Set getDeliveries() {
		return this.deliveries;
	}

	public void setDeliveries(Set deliveries) {
		this.deliveries = deliveries;
	}

}
