package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AccessControl generated by hbm2java
 */
public class AccessControl implements java.io.Serializable {

	private Integer accessControlId;
	private String accessControlName;
	private Set roles = new HashSet(0);

	public AccessControl() {
	}

	public AccessControl(String accessControlName) {
		this.accessControlName = accessControlName;
	}

	public AccessControl(String accessControlName, Set roles) {
		this.accessControlName = accessControlName;
		this.roles = roles;
	}

	public Integer getAccessControlId() {
		return this.accessControlId;
	}

	public void setAccessControlId(Integer accessControlId) {
		this.accessControlId = accessControlId;
	}

	public String getAccessControlName() {
		return this.accessControlName;
	}

	public void setAccessControlName(String accessControlName) {
		this.accessControlName = accessControlName;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

}
