package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * AlembicVersion generated by hbm2java
 */
public class AlembicVersion implements java.io.Serializable {

	private String versionNum;

	public AlembicVersion() {
	}

	public AlembicVersion(String versionNum) {
		this.versionNum = versionNum;
	}

	public String getVersionNum() {
		return this.versionNum;
	}

	public void setVersionNum(String versionNum) {
		this.versionNum = versionNum;
	}

}
