package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AuthenticationEventType generated by hbm2java
 */
public class AuthenticationEventType implements java.io.Serializable {

	private Integer authenticationEventTypeId;
	private String type;
	private Set authenticationLogs = new HashSet(0);

	public AuthenticationEventType() {
	}

	public AuthenticationEventType(String type) {
		this.type = type;
	}

	public AuthenticationEventType(String type, Set authenticationLogs) {
		this.type = type;
		this.authenticationLogs = authenticationLogs;
	}

	public Integer getAuthenticationEventTypeId() {
		return this.authenticationEventTypeId;
	}

	public void setAuthenticationEventTypeId(Integer authenticationEventTypeId) {
		this.authenticationEventTypeId = authenticationEventTypeId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getAuthenticationLogs() {
		return this.authenticationLogs;
	}

	public void setAuthenticationLogs(Set authenticationLogs) {
		this.authenticationLogs = authenticationLogs;
	}

}
