package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuthLog generated by hbm2java
 */
@Entity
@Table(name = "auth_log", catalog = "posbravo")
public class AuthLog implements java.io.Serializable {

	private Integer authLogId;
	private Integer authId;
	private Date logInDate;
	private String logOutDate;
	private Boolean isSuccess;

	public AuthLog() {
	}

	public AuthLog(Integer authId, Date logInDate, String logOutDate,
			Boolean isSuccess) {
		this.authId = authId;
		this.logInDate = logInDate;
		this.logOutDate = logOutDate;
		this.isSuccess = isSuccess;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AuthLogID", unique = true, nullable = false)
	public Integer getAuthLogId() {
		return this.authLogId;
	}

	public void setAuthLogId(Integer authLogId) {
		this.authLogId = authLogId;
	}

	@Column(name = "AuthID")
	public Integer getAuthId() {
		return this.authId;
	}

	public void setAuthId(Integer authId) {
		this.authId = authId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LogInDate", length = 19)
	public Date getLogInDate() {
		return this.logInDate;
	}

	public void setLogInDate(Date logInDate) {
		this.logInDate = logInDate;
	}

	@Column(name = "LogOutDate")
	public String getLogOutDate() {
		return this.logOutDate;
	}

	public void setLogOutDate(String logOutDate) {
		this.logOutDate = logOutDate;
	}

	@Column(name = "IsSuccess")
	public Boolean getIsSuccess() {
		return this.isSuccess;
	}

	public void setIsSuccess(Boolean isSuccess) {
		this.isSuccess = isSuccess;
	}

}
