package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Authentication generated by hbm2java
 */
@Entity
@Table(name = "authentication", catalog = "posbravo")
public class Authentication implements java.io.Serializable {

	private Integer authId;
	private Integer userId;
	private String userName;
	private String password;
	private Integer pin;
	private Boolean isLocked;
	private String maxPwAttempt;
	private Integer maxPinAttempt;

	public Authentication() {
	}

	public Authentication(Integer userId, String userName, String password,
			Integer pin, Boolean isLocked, String maxPwAttempt,
			Integer maxPinAttempt) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.pin = pin;
		this.isLocked = isLocked;
		this.maxPwAttempt = maxPwAttempt;
		this.maxPinAttempt = maxPinAttempt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AuthID", unique = true, nullable = false)
	public Integer getAuthId() {
		return this.authId;
	}

	public void setAuthId(Integer authId) {
		this.authId = authId;
	}

	@Column(name = "UserID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Pin")
	public Integer getPin() {
		return this.pin;
	}

	public void setPin(Integer pin) {
		this.pin = pin;
	}

	@Column(name = "IsLocked")
	public Boolean getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(Boolean isLocked) {
		this.isLocked = isLocked;
	}

	@Column(name = "MaxPwAttempt")
	public String getMaxPwAttempt() {
		return this.maxPwAttempt;
	}

	public void setMaxPwAttempt(String maxPwAttempt) {
		this.maxPwAttempt = maxPwAttempt;
	}

	@Column(name = "MaxPinAttempt")
	public Integer getMaxPinAttempt() {
		return this.maxPinAttempt;
	}

	public void setMaxPinAttempt(Integer maxPinAttempt) {
		this.maxPinAttempt = maxPinAttempt;
	}

}
