package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CartItem generated by hbm2java
 */
public class CartItem implements java.io.Serializable {

	private Integer cartItemId;
	private Service service;
	private Product product;
	private Cart cart;
	private String specialInstructions;
	private int quantity;
	private Date dateAdded;
	private Set discountByItems = new HashSet(0);
	private Set cartItemCustomizations = new HashSet(0);

	public CartItem() {
	}

	public CartItem(Cart cart, int quantity, Date dateAdded) {
		this.cart = cart;
		this.quantity = quantity;
		this.dateAdded = dateAdded;
	}

	public CartItem(Service service, Product product, Cart cart,
			String specialInstructions, int quantity, Date dateAdded,
			Set discountByItems, Set cartItemCustomizations) {
		this.service = service;
		this.product = product;
		this.cart = cart;
		this.specialInstructions = specialInstructions;
		this.quantity = quantity;
		this.dateAdded = dateAdded;
		this.discountByItems = discountByItems;
		this.cartItemCustomizations = cartItemCustomizations;
	}

	public Integer getCartItemId() {
		return this.cartItemId;
	}

	public void setCartItemId(Integer cartItemId) {
		this.cartItemId = cartItemId;
	}

	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	public String getSpecialInstructions() {
		return this.specialInstructions;
	}

	public void setSpecialInstructions(String specialInstructions) {
		this.specialInstructions = specialInstructions;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public Set getDiscountByItems() {
		return this.discountByItems;
	}

	public void setDiscountByItems(Set discountByItems) {
		this.discountByItems = discountByItems;
	}

	public Set getCartItemCustomizations() {
		return this.cartItemCustomizations;
	}

	public void setCartItemCustomizations(Set cartItemCustomizations) {
		this.cartItemCustomizations = cartItemCustomizations;
	}

}
