package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * CartItemCustomization generated by hbm2java
 */
public class CartItemCustomization implements java.io.Serializable {

	private Integer cartItemCustomizationId;
	private CartItem cartItem;
	private ProductCustomization productCustomization;

	public CartItemCustomization() {
	}

	public CartItemCustomization(CartItem cartItem,
			ProductCustomization productCustomization) {
		this.cartItem = cartItem;
		this.productCustomization = productCustomization;
	}

	public Integer getCartItemCustomizationId() {
		return this.cartItemCustomizationId;
	}

	public void setCartItemCustomizationId(Integer cartItemCustomizationId) {
		this.cartItemCustomizationId = cartItemCustomizationId;
	}

	public CartItem getCartItem() {
		return this.cartItem;
	}

	public void setCartItem(CartItem cartItem) {
		this.cartItem = cartItem;
	}

	public ProductCustomization getProductCustomization() {
		return this.productCustomization;
	}

	public void setProductCustomization(
			ProductCustomization productCustomization) {
		this.productCustomization = productCustomization;
	}

}
