package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer cartId;
	private Invoice invoice;
	private CartStatus cartStatus;
	private User user;
	private Set cartItems = new HashSet(0);

	public Cart() {
	}

	public Cart(User user) {
		this.user = user;
	}

	public Cart(Invoice invoice, CartStatus cartStatus, User user, Set cartItems) {
		this.invoice = invoice;
		this.cartStatus = cartStatus;
		this.user = user;
		this.cartItems = cartItems;
	}

	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	public CartStatus getCartStatus() {
		return this.cartStatus;
	}

	public void setCartStatus(CartStatus cartStatus) {
		this.cartStatus = cartStatus;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set getCartItems() {
		return this.cartItems;
	}

	public void setCartItems(Set cartItems) {
		this.cartItems = cartItems;
	}

}
