package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private Integer contactId;
	private User user;
	private Integer cellPhone;
	private Integer homePhone;
	private Integer workPhone;
	private Integer fax;
	private String email;

	public Contact() {
	}

	public Contact(User user, String email) {
		this.user = user;
		this.email = email;
	}

	public Contact(User user, Integer cellPhone, Integer homePhone,
			Integer workPhone, Integer fax, String email) {
		this.user = user;
		this.cellPhone = cellPhone;
		this.homePhone = homePhone;
		this.workPhone = workPhone;
		this.fax = fax;
		this.email = email;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(Integer cellPhone) {
		this.cellPhone = cellPhone;
	}

	public Integer getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(Integer homePhone) {
		this.homePhone = homePhone;
	}

	public Integer getWorkPhone() {
		return this.workPhone;
	}

	public void setWorkPhone(Integer workPhone) {
		this.workPhone = workPhone;
	}

	public Integer getFax() {
		return this.fax;
	}

	public void setFax(Integer fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
