package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Creditcardinfo generated by hbm2java
 */
@Entity
@Table(name = "creditcardinfo", catalog = "posbravo")
public class Creditcardinfo implements java.io.Serializable {

	private Integer ccId;
	private String recordNo;
	private String lastFourDigit;
	private String creditCardNo;
	private String expDate;
	private String cardHolderName;
	private String cardHolderLastName;
	private Integer addressId;
	private String firstSixDigit;
	private String cardType;

	public Creditcardinfo() {
	}

	public Creditcardinfo(String recordNo, String lastFourDigit,
			String creditCardNo, String expDate, String cardHolderName,
			String cardHolderLastName, Integer addressId, String firstSixDigit,
			String cardType) {
		this.recordNo = recordNo;
		this.lastFourDigit = lastFourDigit;
		this.creditCardNo = creditCardNo;
		this.expDate = expDate;
		this.cardHolderName = cardHolderName;
		this.cardHolderLastName = cardHolderLastName;
		this.addressId = addressId;
		this.firstSixDigit = firstSixDigit;
		this.cardType = cardType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Cc_ID", unique = true, nullable = false)
	public Integer getCcId() {
		return this.ccId;
	}

	public void setCcId(Integer ccId) {
		this.ccId = ccId;
	}

	@Column(name = "RecordNo")
	public String getRecordNo() {
		return this.recordNo;
	}

	public void setRecordNo(String recordNo) {
		this.recordNo = recordNo;
	}

	@Column(name = "LastFourDigit")
	public String getLastFourDigit() {
		return this.lastFourDigit;
	}

	public void setLastFourDigit(String lastFourDigit) {
		this.lastFourDigit = lastFourDigit;
	}

	@Column(name = "CreditCardNo")
	public String getCreditCardNo() {
		return this.creditCardNo;
	}

	public void setCreditCardNo(String creditCardNo) {
		this.creditCardNo = creditCardNo;
	}

	@Column(name = "ExpDate")
	public String getExpDate() {
		return this.expDate;
	}

	public void setExpDate(String expDate) {
		this.expDate = expDate;
	}

	@Column(name = "CardHolderName")
	public String getCardHolderName() {
		return this.cardHolderName;
	}

	public void setCardHolderName(String cardHolderName) {
		this.cardHolderName = cardHolderName;
	}

	@Column(name = "CardHolderLastName")
	public String getCardHolderLastName() {
		return this.cardHolderLastName;
	}

	public void setCardHolderLastName(String cardHolderLastName) {
		this.cardHolderLastName = cardHolderLastName;
	}

	@Column(name = "AddressID")
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "FirstSixDigit")
	public String getFirstSixDigit() {
		return this.firstSixDigit;
	}

	public void setFirstSixDigit(String firstSixDigit) {
		this.firstSixDigit = firstSixDigit;
	}

	@Column(name = "CardType")
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

}
