package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Delivery generated by hbm2java
 */
@Entity
@Table(name = "delivery", catalog = "posbravo")
public class Delivery implements java.io.Serializable {

	private Integer deliveryId;
	private Integer zoneId;
	private Integer courierId;
	private Integer receipientId;
	private Date departureDate;
	private Date arrivalDate;
	private Integer invoiceId;

	public Delivery() {
	}

	public Delivery(Integer zoneId, Integer courierId, Integer receipientId,
			Date departureDate, Date arrivalDate, Integer invoiceId) {
		this.zoneId = zoneId;
		this.courierId = courierId;
		this.receipientId = receipientId;
		this.departureDate = departureDate;
		this.arrivalDate = arrivalDate;
		this.invoiceId = invoiceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DeliveryID", unique = true, nullable = false)
	public Integer getDeliveryId() {
		return this.deliveryId;
	}

	public void setDeliveryId(Integer deliveryId) {
		this.deliveryId = deliveryId;
	}

	@Column(name = "ZoneID")
	public Integer getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(Integer zoneId) {
		this.zoneId = zoneId;
	}

	@Column(name = "CourierID")
	public Integer getCourierId() {
		return this.courierId;
	}

	public void setCourierId(Integer courierId) {
		this.courierId = courierId;
	}

	@Column(name = "ReceipientID")
	public Integer getReceipientId() {
		return this.receipientId;
	}

	public void setReceipientId(Integer receipientId) {
		this.receipientId = receipientId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DepartureDate", length = 19)
	public Date getDepartureDate() {
		return this.departureDate;
	}

	public void setDepartureDate(Date departureDate) {
		this.departureDate = departureDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ArrivalDate", length = 19)
	public Date getArrivalDate() {
		return this.arrivalDate;
	}

	public void setArrivalDate(Date arrivalDate) {
		this.arrivalDate = arrivalDate;
	}

	@Column(name = "InvoiceID")
	public Integer getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

}
