package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Delivery generated by hbm2java
 */
public class Delivery implements java.io.Serializable {

	private Integer deliveryId;
	private Invoice invoice;
	private Zone zone;
	private User userByCourierId;
	private User userByRecipientId;
	private Date dateOfEstimatedDeparture;
	private Date dateOfEstimatedArrival;
	private Date dateOfDeparture;
	private Date dateOfArrival;

	public Delivery() {
	}

	public Delivery(Invoice invoice, User userByRecipientId) {
		this.invoice = invoice;
		this.userByRecipientId = userByRecipientId;
	}

	public Delivery(Invoice invoice, Zone zone, User userByCourierId,
			User userByRecipientId, Date dateOfEstimatedDeparture,
			Date dateOfEstimatedArrival, Date dateOfDeparture,
			Date dateOfArrival) {
		this.invoice = invoice;
		this.zone = zone;
		this.userByCourierId = userByCourierId;
		this.userByRecipientId = userByRecipientId;
		this.dateOfEstimatedDeparture = dateOfEstimatedDeparture;
		this.dateOfEstimatedArrival = dateOfEstimatedArrival;
		this.dateOfDeparture = dateOfDeparture;
		this.dateOfArrival = dateOfArrival;
	}

	public Integer getDeliveryId() {
		return this.deliveryId;
	}

	public void setDeliveryId(Integer deliveryId) {
		this.deliveryId = deliveryId;
	}

	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	public Zone getZone() {
		return this.zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	public User getUserByCourierId() {
		return this.userByCourierId;
	}

	public void setUserByCourierId(User userByCourierId) {
		this.userByCourierId = userByCourierId;
	}

	public User getUserByRecipientId() {
		return this.userByRecipientId;
	}

	public void setUserByRecipientId(User userByRecipientId) {
		this.userByRecipientId = userByRecipientId;
	}

	public Date getDateOfEstimatedDeparture() {
		return this.dateOfEstimatedDeparture;
	}

	public void setDateOfEstimatedDeparture(Date dateOfEstimatedDeparture) {
		this.dateOfEstimatedDeparture = dateOfEstimatedDeparture;
	}

	public Date getDateOfEstimatedArrival() {
		return this.dateOfEstimatedArrival;
	}

	public void setDateOfEstimatedArrival(Date dateOfEstimatedArrival) {
		this.dateOfEstimatedArrival = dateOfEstimatedArrival;
	}

	public Date getDateOfDeparture() {
		return this.dateOfDeparture;
	}

	public void setDateOfDeparture(Date dateOfDeparture) {
		this.dateOfDeparture = dateOfDeparture;
	}

	public Date getDateOfArrival() {
		return this.dateOfArrival;
	}

	public void setDateOfArrival(Date dateOfArrival) {
		this.dateOfArrival = dateOfArrival;
	}

}
