package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DiningTableStatus generated by hbm2java
 */
public class DiningTableStatus implements java.io.Serializable {

	private Integer diningTableStatusId;
	private String status;
	private Set diningTables = new HashSet(0);

	public DiningTableStatus() {
	}

	public DiningTableStatus(String status) {
		this.status = status;
	}

	public DiningTableStatus(String status, Set diningTables) {
		this.status = status;
		this.diningTables = diningTables;
	}

	public Integer getDiningTableStatusId() {
		return this.diningTableStatusId;
	}

	public void setDiningTableStatusId(Integer diningTableStatusId) {
		this.diningTableStatusId = diningTableStatusId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getDiningTables() {
		return this.diningTables;
	}

	public void setDiningTables(Set diningTables) {
		this.diningTables = diningTables;
	}

}
