package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Diningtable generated by hbm2java
 */
@Entity
@Table(name = "diningtable", catalog = "posbravo")
public class Diningtable implements java.io.Serializable {

	private Integer tableId;
	private String tableDescription;
	private Integer tableTypeId;
	private Integer capacity;
	private Boolean smoking;
	private Boolean status;
	private Date lastModifiedDate;
	private Date addDate;

	public Diningtable() {
	}

	public Diningtable(String tableDescription, Integer tableTypeId,
			Integer capacity, Boolean smoking, Boolean status,
			Date lastModifiedDate, Date addDate) {
		this.tableDescription = tableDescription;
		this.tableTypeId = tableTypeId;
		this.capacity = capacity;
		this.smoking = smoking;
		this.status = status;
		this.lastModifiedDate = lastModifiedDate;
		this.addDate = addDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TableID", unique = true, nullable = false)
	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	@Column(name = "TableDescription")
	public String getTableDescription() {
		return this.tableDescription;
	}

	public void setTableDescription(String tableDescription) {
		this.tableDescription = tableDescription;
	}

	@Column(name = "TableTypeID")
	public Integer getTableTypeId() {
		return this.tableTypeId;
	}

	public void setTableTypeId(Integer tableTypeId) {
		this.tableTypeId = tableTypeId;
	}

	@Column(name = "Capacity")
	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	@Column(name = "Smoking")
	public Boolean getSmoking() {
		return this.smoking;
	}

	public void setSmoking(Boolean smoking) {
		this.smoking = smoking;
	}

	@Column(name = "Status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AddDate", length = 19)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

}
