package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DiningTable generated by hbm2java
 */
public class DiningTable implements java.io.Serializable {

	private Integer diningTableId;
	private DiningTableType diningTableType;
	private DiningTableStatus diningTableStatus;
	private String description;
	private int capacity;
	private boolean smoking;
	private Date dateLastModified;
	private Date dateAdded;
	private Set invoices = new HashSet(0);

	public DiningTable() {
	}

	public DiningTable(DiningTableStatus diningTableStatus, int capacity,
			boolean smoking, Date dateLastModified, Date dateAdded) {
		this.diningTableStatus = diningTableStatus;
		this.capacity = capacity;
		this.smoking = smoking;
		this.dateLastModified = dateLastModified;
		this.dateAdded = dateAdded;
	}

	public DiningTable(DiningTableType diningTableType,
			DiningTableStatus diningTableStatus, String description,
			int capacity, boolean smoking, Date dateLastModified,
			Date dateAdded, Set invoices) {
		this.diningTableType = diningTableType;
		this.diningTableStatus = diningTableStatus;
		this.description = description;
		this.capacity = capacity;
		this.smoking = smoking;
		this.dateLastModified = dateLastModified;
		this.dateAdded = dateAdded;
		this.invoices = invoices;
	}

	public Integer getDiningTableId() {
		return this.diningTableId;
	}

	public void setDiningTableId(Integer diningTableId) {
		this.diningTableId = diningTableId;
	}

	public DiningTableType getDiningTableType() {
		return this.diningTableType;
	}

	public void setDiningTableType(DiningTableType diningTableType) {
		this.diningTableType = diningTableType;
	}

	public DiningTableStatus getDiningTableStatus() {
		return this.diningTableStatus;
	}

	public void setDiningTableStatus(DiningTableStatus diningTableStatus) {
		this.diningTableStatus = diningTableStatus;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	public boolean isSmoking() {
		return this.smoking;
	}

	public void setSmoking(boolean smoking) {
		this.smoking = smoking;
	}

	public Date getDateLastModified() {
		return this.dateLastModified;
	}

	public void setDateLastModified(Date dateLastModified) {
		this.dateLastModified = dateLastModified;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public Set getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set invoices) {
		this.invoices = invoices;
	}

}
