package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiscountByItemId generated by hbm2java
 */
@Embeddable
public class DiscountByItemId implements java.io.Serializable {

	private Integer purchaseId;
	private Integer promId;

	public DiscountByItemId() {
	}

	public DiscountByItemId(Integer purchaseId, Integer promId) {
		this.purchaseId = purchaseId;
		this.promId = promId;
	}

	@Column(name = "PurchaseId")
	public Integer getPurchaseId() {
		return this.purchaseId;
	}

	public void setPurchaseId(Integer purchaseId) {
		this.purchaseId = purchaseId;
	}

	@Column(name = "PromId")
	public Integer getPromId() {
		return this.promId;
	}

	public void setPromId(Integer promId) {
		this.promId = promId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiscountByItemId))
			return false;
		DiscountByItemId castOther = (DiscountByItemId) other;

		return ((this.getPurchaseId() == castOther.getPurchaseId()) || (this
				.getPurchaseId() != null && castOther.getPurchaseId() != null && this
				.getPurchaseId().equals(castOther.getPurchaseId())))
				&& ((this.getPromId() == castOther.getPromId()) || (this
						.getPromId() != null && castOther.getPromId() != null && this
						.getPromId().equals(castOther.getPromId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPurchaseId() == null ? 0 : this.getPurchaseId()
						.hashCode());
		result = 37 * result
				+ (getPromId() == null ? 0 : this.getPromId().hashCode());
		return result;
	}

}
