package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * DiscountByInvoice generated by hbm2java
 */
public class DiscountByInvoice implements java.io.Serializable {

	private Integer discountByInvoiceId;
	private Invoice invoice;
	private Promotion promotion;

	public DiscountByInvoice() {
	}

	public DiscountByInvoice(Invoice invoice, Promotion promotion) {
		this.invoice = invoice;
		this.promotion = promotion;
	}

	public Integer getDiscountByInvoiceId() {
		return this.discountByInvoiceId;
	}

	public void setDiscountByInvoiceId(Integer discountByInvoiceId) {
		this.discountByInvoiceId = discountByInvoiceId;
	}

	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

}
