package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * DiscountByItem generated by hbm2java
 */
public class DiscountByItem implements java.io.Serializable {

	private Integer discountByItemId;
	private Promotion promotion;
	private CartItem cartItem;

	public DiscountByItem() {
	}

	public DiscountByItem(Promotion promotion, CartItem cartItem) {
		this.promotion = promotion;
		this.cartItem = cartItem;
	}

	public Integer getDiscountByItemId() {
		return this.discountByItemId;
	}

	public void setDiscountByItemId(Integer discountByItemId) {
		this.discountByItemId = discountByItemId;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public CartItem getCartItem() {
		return this.cartItem;
	}

	public void setCartItem(CartItem cartItem) {
		this.cartItem = cartItem;
	}

}
