package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceStatus generated by hbm2java
 */
public class InvoiceStatus implements java.io.Serializable {

	private Integer invoiceStatusId;
	private Invoice invoice;
	private Date dateLastModified;
	private Set payments = new HashSet(0);

	public InvoiceStatus() {
	}

	public InvoiceStatus(Invoice invoice, Date dateLastModified) {
		this.invoice = invoice;
		this.dateLastModified = dateLastModified;
	}

	public InvoiceStatus(Invoice invoice, Date dateLastModified, Set payments) {
		this.invoice = invoice;
		this.dateLastModified = dateLastModified;
		this.payments = payments;
	}

	public Integer getInvoiceStatusId() {
		return this.invoiceStatusId;
	}

	public void setInvoiceStatusId(Integer invoiceStatusId) {
		this.invoiceStatusId = invoiceStatusId;
	}

	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	public Date getDateLastModified() {
		return this.dateLastModified;
	}

	public void setDateLastModified(Date dateLastModified) {
		this.dateLastModified = dateLastModified;
	}

	public Set getPayments() {
		return this.payments;
	}

	public void setPayments(Set payments) {
		this.payments = payments;
	}

}
