package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice implements java.io.Serializable {

	private Integer invoiceId;
	private ShippingClass shippingClass;
	private Promotion promotion;
	private DiningTable diningTable;
	private Date dateSent;
	private BigDecimal amount;
	private Date dateDue;
	private Integer partySize;
	private Set invoiceStatuses = new HashSet(0);
	private Set deliveries = new HashSet(0);
	private Set carts = new HashSet(0);
	private Set discountByInvoices = new HashSet(0);

	public Invoice() {
	}

	public Invoice(Date dateSent, BigDecimal amount, Date dateDue) {
		this.dateSent = dateSent;
		this.amount = amount;
		this.dateDue = dateDue;
	}

	public Invoice(ShippingClass shippingClass, Promotion promotion,
			DiningTable diningTable, Date dateSent, BigDecimal amount,
			Date dateDue, Integer partySize, Set invoiceStatuses,
			Set deliveries, Set carts, Set discountByInvoices) {
		this.shippingClass = shippingClass;
		this.promotion = promotion;
		this.diningTable = diningTable;
		this.dateSent = dateSent;
		this.amount = amount;
		this.dateDue = dateDue;
		this.partySize = partySize;
		this.invoiceStatuses = invoiceStatuses;
		this.deliveries = deliveries;
		this.carts = carts;
		this.discountByInvoices = discountByInvoices;
	}

	public Integer getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

	public ShippingClass getShippingClass() {
		return this.shippingClass;
	}

	public void setShippingClass(ShippingClass shippingClass) {
		this.shippingClass = shippingClass;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public DiningTable getDiningTable() {
		return this.diningTable;
	}

	public void setDiningTable(DiningTable diningTable) {
		this.diningTable = diningTable;
	}

	public Date getDateSent() {
		return this.dateSent;
	}

	public void setDateSent(Date dateSent) {
		this.dateSent = dateSent;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Date getDateDue() {
		return this.dateDue;
	}

	public void setDateDue(Date dateDue) {
		this.dateDue = dateDue;
	}

	public Integer getPartySize() {
		return this.partySize;
	}

	public void setPartySize(Integer partySize) {
		this.partySize = partySize;
	}

	public Set getInvoiceStatuses() {
		return this.invoiceStatuses;
	}

	public void setInvoiceStatuses(Set invoiceStatuses) {
		this.invoiceStatuses = invoiceStatuses;
	}

	public Set getDeliveries() {
		return this.deliveries;
	}

	public void setDeliveries(Set deliveries) {
		this.deliveries = deliveries;
	}

	public Set getCarts() {
		return this.carts;
	}

	public void setCarts(Set carts) {
		this.carts = carts;
	}

	public Set getDiscountByInvoices() {
		return this.discountByInvoices;
	}

	public void setDiscountByInvoices(Set discountByInvoices) {
		this.discountByInvoices = discountByInvoices;
	}

}
