package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvoiceStatus generated by hbm2java
 */
@Entity
@Table(name = "invoice_status", catalog = "posbravo")
public class InvoiceStatus implements java.io.Serializable {

	private int invoiceId;
	private String status;
	private Date lastModifiedDate;

	public InvoiceStatus() {
	}

	public InvoiceStatus(int invoiceId) {
		this.invoiceId = invoiceId;
	}

	public InvoiceStatus(int invoiceId, String status, Date lastModifiedDate) {
		this.invoiceId = invoiceId;
		this.status = status;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@Column(name = "InvoiceID", unique = true, nullable = false)
	public int getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(int invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "Status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
