package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Labor generated by hbm2java
 */
public class Labor implements java.io.Serializable {

	private Integer laborId;
	private Rates rates;
	private String serviceDescription;
	private Set services = new HashSet(0);

	public Labor() {
	}

	public Labor(Rates rates, String serviceDescription, Set services) {
		this.rates = rates;
		this.serviceDescription = serviceDescription;
		this.services = services;
	}

	public Integer getLaborId() {
		return this.laborId;
	}

	public void setLaborId(Integer laborId) {
		this.laborId = laborId;
	}

	public Rates getRates() {
		return this.rates;
	}

	public void setRates(Rates rates) {
		this.rates = rates;
	}

	public String getServiceDescription() {
		return this.serviceDescription;
	}

	public void setServiceDescription(String serviceDescription) {
		this.serviceDescription = serviceDescription;
	}

	public Set getServices() {
		return this.services;
	}

	public void setServices(Set services) {
		this.services = services;
	}

}
