package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Labor generated by hbm2java
 */
@Entity
@Table(name = "labor", catalog = "posbravo")
public class Labor implements java.io.Serializable {

	private Integer laborId;
	private String serviceDescription;
	private Integer ratesId;

	public Labor() {
	}

	public Labor(String serviceDescription, Integer ratesId) {
		this.serviceDescription = serviceDescription;
		this.ratesId = ratesId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LaborId", unique = true, nullable = false)
	public Integer getLaborId() {
		return this.laborId;
	}

	public void setLaborId(Integer laborId) {
		this.laborId = laborId;
	}

	@Column(name = "ServiceDescription")
	public String getServiceDescription() {
		return this.serviceDescription;
	}

	public void setServiceDescription(String serviceDescription) {
		this.serviceDescription = serviceDescription;
	}

	@Column(name = "RatesId")
	public Integer getRatesId() {
		return this.ratesId;
	}

	public void setRatesId(Integer ratesId) {
		this.ratesId = ratesId;
	}

}
