package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "posbravo")
public class Payment implements java.io.Serializable {

	private Integer paymentId;
	private String paymentType;
	private Date paymentDate;
	private Integer invoiceNo;
	private Integer ccId;
	private Integer preAuthId;
	private Integer preAuthCapId;
	private Integer reverseId;
	private Integer returnId;
	private Integer adjustId;
	private Integer saleId;

	public Payment() {
	}

	public Payment(String paymentType, Date paymentDate, Integer invoiceNo,
			Integer ccId, Integer preAuthId, Integer preAuthCapId,
			Integer reverseId, Integer returnId, Integer adjustId,
			Integer saleId) {
		this.paymentType = paymentType;
		this.paymentDate = paymentDate;
		this.invoiceNo = invoiceNo;
		this.ccId = ccId;
		this.preAuthId = preAuthId;
		this.preAuthCapId = preAuthCapId;
		this.reverseId = reverseId;
		this.returnId = returnId;
		this.adjustId = adjustId;
		this.saleId = saleId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PaymentId", unique = true, nullable = false)
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "PaymentType")
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PaymentDate", length = 19)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "InvoiceNo")
	public Integer getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(Integer invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "CcID")
	public Integer getCcId() {
		return this.ccId;
	}

	public void setCcId(Integer ccId) {
		this.ccId = ccId;
	}

	@Column(name = "PreAuthID")
	public Integer getPreAuthId() {
		return this.preAuthId;
	}

	public void setPreAuthId(Integer preAuthId) {
		this.preAuthId = preAuthId;
	}

	@Column(name = "PreAuthCapID")
	public Integer getPreAuthCapId() {
		return this.preAuthCapId;
	}

	public void setPreAuthCapId(Integer preAuthCapId) {
		this.preAuthCapId = preAuthCapId;
	}

	@Column(name = "ReverseID")
	public Integer getReverseId() {
		return this.reverseId;
	}

	public void setReverseId(Integer reverseId) {
		this.reverseId = reverseId;
	}

	@Column(name = "ReturnID")
	public Integer getReturnId() {
		return this.returnId;
	}

	public void setReturnId(Integer returnId) {
		this.returnId = returnId;
	}

	@Column(name = "AdjustID")
	public Integer getAdjustId() {
		return this.adjustId;
	}

	public void setAdjustId(Integer adjustId) {
		this.adjustId = adjustId;
	}

	@Column(name = "SaleID")
	public Integer getSaleId() {
		return this.saleId;
	}

	public void setSaleId(Integer saleId) {
		this.saleId = saleId;
	}

}
