package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private Integer paymentId;
	private PaymentPreAuthCapture paymentPreAuthCapture;
	private PaymentSale paymentSale;
	private CreditCardInfo creditCardInfo;
	private PaymentReverse paymentReverse;
	private PaymentType paymentType;
	private PaymentReturn paymentReturn;
	private InvoiceStatus invoiceStatus;
	private PaymentAdjust paymentAdjust;
	private PaymentPreAuth paymentPreAuth;
	private Date dateOfPayment;

	public Payment() {
	}

	public Payment(PaymentType paymentType, Date dateOfPayment) {
		this.paymentType = paymentType;
		this.dateOfPayment = dateOfPayment;
	}

	public Payment(PaymentPreAuthCapture paymentPreAuthCapture,
			PaymentSale paymentSale, CreditCardInfo creditCardInfo,
			PaymentReverse paymentReverse, PaymentType paymentType,
			PaymentReturn paymentReturn, InvoiceStatus invoiceStatus,
			PaymentAdjust paymentAdjust, PaymentPreAuth paymentPreAuth,
			Date dateOfPayment) {
		this.paymentPreAuthCapture = paymentPreAuthCapture;
		this.paymentSale = paymentSale;
		this.creditCardInfo = creditCardInfo;
		this.paymentReverse = paymentReverse;
		this.paymentType = paymentType;
		this.paymentReturn = paymentReturn;
		this.invoiceStatus = invoiceStatus;
		this.paymentAdjust = paymentAdjust;
		this.paymentPreAuth = paymentPreAuth;
		this.dateOfPayment = dateOfPayment;
	}

	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	public PaymentPreAuthCapture getPaymentPreAuthCapture() {
		return this.paymentPreAuthCapture;
	}

	public void setPaymentPreAuthCapture(
			PaymentPreAuthCapture paymentPreAuthCapture) {
		this.paymentPreAuthCapture = paymentPreAuthCapture;
	}

	public PaymentSale getPaymentSale() {
		return this.paymentSale;
	}

	public void setPaymentSale(PaymentSale paymentSale) {
		this.paymentSale = paymentSale;
	}

	public CreditCardInfo getCreditCardInfo() {
		return this.creditCardInfo;
	}

	public void setCreditCardInfo(CreditCardInfo creditCardInfo) {
		this.creditCardInfo = creditCardInfo;
	}

	public PaymentReverse getPaymentReverse() {
		return this.paymentReverse;
	}

	public void setPaymentReverse(PaymentReverse paymentReverse) {
		this.paymentReverse = paymentReverse;
	}

	public PaymentType getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(PaymentType paymentType) {
		this.paymentType = paymentType;
	}

	public PaymentReturn getPaymentReturn() {
		return this.paymentReturn;
	}

	public void setPaymentReturn(PaymentReturn paymentReturn) {
		this.paymentReturn = paymentReturn;
	}

	public InvoiceStatus getInvoiceStatus() {
		return this.invoiceStatus;
	}

	public void setInvoiceStatus(InvoiceStatus invoiceStatus) {
		this.invoiceStatus = invoiceStatus;
	}

	public PaymentAdjust getPaymentAdjust() {
		return this.paymentAdjust;
	}

	public void setPaymentAdjust(PaymentAdjust paymentAdjust) {
		this.paymentAdjust = paymentAdjust;
	}

	public PaymentPreAuth getPaymentPreAuth() {
		return this.paymentPreAuth;
	}

	public void setPaymentPreAuth(PaymentPreAuth paymentPreAuth) {
		this.paymentPreAuth = paymentPreAuth;
	}

	public Date getDateOfPayment() {
		return this.dateOfPayment;
	}

	public void setDateOfPayment(Date dateOfPayment) {
		this.dateOfPayment = dateOfPayment;
	}

}
