package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PreauthCapture generated by hbm2java
 */
@Entity
@Table(name = "preauth_capture", catalog = "posbravo")
public class PreauthCapture implements java.io.Serializable {

	private Integer preAuthCapId;
	private String dsixreturnCode;
	private String cmdStatus;
	private String textResponse;
	private String authCode;
	private Integer refNo;
	private BigDecimal purchaseAmount;
	private BigDecimal authorizeAmount;
	private BigDecimal gratuity;
	private String acqRefData;
	private String recordNo;
	private String processData;

	public PreauthCapture() {
	}

	public PreauthCapture(String dsixreturnCode, String cmdStatus,
			String textResponse, String authCode, Integer refNo,
			BigDecimal purchaseAmount, BigDecimal authorizeAmount,
			BigDecimal gratuity, String acqRefData, String recordNo,
			String processData) {
		this.dsixreturnCode = dsixreturnCode;
		this.cmdStatus = cmdStatus;
		this.textResponse = textResponse;
		this.authCode = authCode;
		this.refNo = refNo;
		this.purchaseAmount = purchaseAmount;
		this.authorizeAmount = authorizeAmount;
		this.gratuity = gratuity;
		this.acqRefData = acqRefData;
		this.recordNo = recordNo;
		this.processData = processData;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PreAuthCapID", unique = true, nullable = false)
	public Integer getPreAuthCapId() {
		return this.preAuthCapId;
	}

	public void setPreAuthCapId(Integer preAuthCapId) {
		this.preAuthCapId = preAuthCapId;
	}

	@Column(name = "DSIXReturnCode")
	public String getDsixreturnCode() {
		return this.dsixreturnCode;
	}

	public void setDsixreturnCode(String dsixreturnCode) {
		this.dsixreturnCode = dsixreturnCode;
	}

	@Column(name = "CmdStatus")
	public String getCmdStatus() {
		return this.cmdStatus;
	}

	public void setCmdStatus(String cmdStatus) {
		this.cmdStatus = cmdStatus;
	}

	@Column(name = "TextResponse")
	public String getTextResponse() {
		return this.textResponse;
	}

	public void setTextResponse(String textResponse) {
		this.textResponse = textResponse;
	}

	@Column(name = "AuthCode")
	public String getAuthCode() {
		return this.authCode;
	}

	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}

	@Column(name = "RefNo")
	public Integer getRefNo() {
		return this.refNo;
	}

	public void setRefNo(Integer refNo) {
		this.refNo = refNo;
	}

	@Column(name = "PurchaseAmount", scale = 4)
	public BigDecimal getPurchaseAmount() {
		return this.purchaseAmount;
	}

	public void setPurchaseAmount(BigDecimal purchaseAmount) {
		this.purchaseAmount = purchaseAmount;
	}

	@Column(name = "AuthorizeAmount", scale = 4)
	public BigDecimal getAuthorizeAmount() {
		return this.authorizeAmount;
	}

	public void setAuthorizeAmount(BigDecimal authorizeAmount) {
		this.authorizeAmount = authorizeAmount;
	}

	@Column(name = "Gratuity", scale = 4)
	public BigDecimal getGratuity() {
		return this.gratuity;
	}

	public void setGratuity(BigDecimal gratuity) {
		this.gratuity = gratuity;
	}

	@Column(name = "AcqRefData")
	public String getAcqRefData() {
		return this.acqRefData;
	}

	public void setAcqRefData(String acqRefData) {
		this.acqRefData = acqRefData;
	}

	@Column(name = "RecordNo")
	public String getRecordNo() {
		return this.recordNo;
	}

	public void setRecordNo(String recordNo) {
		this.recordNo = recordNo;
	}

	@Column(name = "ProcessData")
	public String getProcessData() {
		return this.processData;
	}

	public void setProcessData(String processData) {
		this.processData = processData;
	}

}
