package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProductCustomizationToGroup generated by hbm2java
 */
public class ProductCustomizationToGroup implements java.io.Serializable {

	private Integer productCustomizationToGroupId;
	private ProductCustomizationGroup productCustomizationGroup;
	private ProductCustomization productCustomization;

	public ProductCustomizationToGroup() {
	}

	public ProductCustomizationToGroup(
			ProductCustomizationGroup productCustomizationGroup,
			ProductCustomization productCustomization) {
		this.productCustomizationGroup = productCustomizationGroup;
		this.productCustomization = productCustomization;
	}

	public Integer getProductCustomizationToGroupId() {
		return this.productCustomizationToGroupId;
	}

	public void setProductCustomizationToGroupId(
			Integer productCustomizationToGroupId) {
		this.productCustomizationToGroupId = productCustomizationToGroupId;
	}

	public ProductCustomizationGroup getProductCustomizationGroup() {
		return this.productCustomizationGroup;
	}

	public void setProductCustomizationGroup(
			ProductCustomizationGroup productCustomizationGroup) {
		this.productCustomizationGroup = productCustomizationGroup;
	}

	public ProductCustomization getProductCustomization() {
		return this.productCustomization;
	}

	public void setProductCustomization(
			ProductCustomization productCustomization) {
		this.productCustomization = productCustomization;
	}

}
