package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductTag generated by hbm2java
 */
public class ProductTag implements java.io.Serializable {

	private Integer productTagId;
	private String type;
	private Set productTagToProducts = new HashSet(0);

	public ProductTag() {
	}

	public ProductTag(String type) {
		this.type = type;
	}

	public ProductTag(String type, Set productTagToProducts) {
		this.type = type;
		this.productTagToProducts = productTagToProducts;
	}

	public Integer getProductTagId() {
		return this.productTagId;
	}

	public void setProductTagId(Integer productTagId) {
		this.productTagId = productTagId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getProductTagToProducts() {
		return this.productTagToProducts;
	}

	public void setProductTagToProducts(Set productTagToProducts) {
		this.productTagToProducts = productTagToProducts;
	}

}
