package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "posbravo")
public class Product implements java.io.Serializable {

	private Integer itemNo;
	private String itemDescription;
	private BigDecimal price;
	private String barcode;
	private String size;
	private String image;
	private Date addDate;
	private Date lastModifiedDate;
	private Date dateAvailable;
	private String weight;
	private String taxClassId;

	public Product() {
	}

	public Product(String itemDescription, BigDecimal price, String barcode,
			String size, String image, Date addDate, Date lastModifiedDate,
			Date dateAvailable, String weight, String taxClassId) {
		this.itemDescription = itemDescription;
		this.price = price;
		this.barcode = barcode;
		this.size = size;
		this.image = image;
		this.addDate = addDate;
		this.lastModifiedDate = lastModifiedDate;
		this.dateAvailable = dateAvailable;
		this.weight = weight;
		this.taxClassId = taxClassId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ItemNo", unique = true, nullable = false)
	public Integer getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(Integer itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "ItemDescription")
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "Price", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "Barcode")
	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	@Column(name = "Size")
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "Image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AddDate", length = 19)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateAvailable", length = 19)
	public Date getDateAvailable() {
		return this.dateAvailable;
	}

	public void setDateAvailable(Date dateAvailable) {
		this.dateAvailable = dateAvailable;
	}

	@Column(name = "Weight")
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name = "TaxClassID")
	public String getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(String taxClassId) {
		this.taxClassId = taxClassId;
	}

}
