package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PromotionGroup generated by hbm2java
 */
public class PromotionGroup implements java.io.Serializable {

	private Integer promotionGroupId;
	private String groupName;
	private Set promotionToPromotionGroups = new HashSet(0);
	private Set promotionUsages = new HashSet(0);
	private Set userPromotions = new HashSet(0);

	public PromotionGroup() {
	}

	public PromotionGroup(String groupName, Set promotionToPromotionGroups,
			Set promotionUsages, Set userPromotions) {
		this.groupName = groupName;
		this.promotionToPromotionGroups = promotionToPromotionGroups;
		this.promotionUsages = promotionUsages;
		this.userPromotions = userPromotions;
	}

	public Integer getPromotionGroupId() {
		return this.promotionGroupId;
	}

	public void setPromotionGroupId(Integer promotionGroupId) {
		this.promotionGroupId = promotionGroupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Set getPromotionToPromotionGroups() {
		return this.promotionToPromotionGroups;
	}

	public void setPromotionToPromotionGroups(Set promotionToPromotionGroups) {
		this.promotionToPromotionGroups = promotionToPromotionGroups;
	}

	public Set getPromotionUsages() {
		return this.promotionUsages;
	}

	public void setPromotionUsages(Set promotionUsages) {
		this.promotionUsages = promotionUsages;
	}

	public Set getUserPromotions() {
		return this.userPromotions;
	}

	public void setUserPromotions(Set userPromotions) {
		this.userPromotions = userPromotions;
	}

}
