package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion", catalog = "posbravo")
public class Promotion implements java.io.Serializable {

	private Integer promId;
	private Integer discountPercentage;

	public Promotion() {
	}

	public Promotion(Integer discountPercentage) {
		this.discountPercentage = discountPercentage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PromId", unique = true, nullable = false)
	public Integer getPromId() {
		return this.promId;
	}

	public void setPromId(Integer promId) {
		this.promId = promId;
	}

	@Column(name = "DiscountPercentage")
	public Integer getDiscountPercentage() {
		return this.discountPercentage;
	}

	public void setDiscountPercentage(Integer discountPercentage) {
		this.discountPercentage = discountPercentage;
	}

}
