package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Promotion generated by hbm2java
 */
public class Promotion implements java.io.Serializable {

	private Integer promotionId;
	private String name;
	private BigDecimal discountPercent;
	private BigDecimal discountAmount;
	private Date startDate;
	private Date endDate;
	private String vanityCode;
	private Integer usesPerCustomer;
	private Set invoices = new HashSet(0);
	private Set promotionToPromotionGroups = new HashSet(0);
	private Set promotionUsages = new HashSet(0);
	private Set discountByItems = new HashSet(0);
	private Set discountByInvoices = new HashSet(0);
	private Set restaurantPromotions = new HashSet(0);

	public Promotion() {
	}

	public Promotion(String name, BigDecimal discountPercent,
			BigDecimal discountAmount) {
		this.name = name;
		this.discountPercent = discountPercent;
		this.discountAmount = discountAmount;
	}

	public Promotion(String name, BigDecimal discountPercent,
			BigDecimal discountAmount, Date startDate, Date endDate,
			String vanityCode, Integer usesPerCustomer, Set invoices,
			Set promotionToPromotionGroups, Set promotionUsages,
			Set discountByItems, Set discountByInvoices,
			Set restaurantPromotions) {
		this.name = name;
		this.discountPercent = discountPercent;
		this.discountAmount = discountAmount;
		this.startDate = startDate;
		this.endDate = endDate;
		this.vanityCode = vanityCode;
		this.usesPerCustomer = usesPerCustomer;
		this.invoices = invoices;
		this.promotionToPromotionGroups = promotionToPromotionGroups;
		this.promotionUsages = promotionUsages;
		this.discountByItems = discountByItems;
		this.discountByInvoices = discountByInvoices;
		this.restaurantPromotions = restaurantPromotions;
	}

	public Integer getPromotionId() {
		return this.promotionId;
	}

	public void setPromotionId(Integer promotionId) {
		this.promotionId = promotionId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getDiscountPercent() {
		return this.discountPercent;
	}

	public void setDiscountPercent(BigDecimal discountPercent) {
		this.discountPercent = discountPercent;
	}

	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getVanityCode() {
		return this.vanityCode;
	}

	public void setVanityCode(String vanityCode) {
		this.vanityCode = vanityCode;
	}

	public Integer getUsesPerCustomer() {
		return this.usesPerCustomer;
	}

	public void setUsesPerCustomer(Integer usesPerCustomer) {
		this.usesPerCustomer = usesPerCustomer;
	}

	public Set getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set invoices) {
		this.invoices = invoices;
	}

	public Set getPromotionToPromotionGroups() {
		return this.promotionToPromotionGroups;
	}

	public void setPromotionToPromotionGroups(Set promotionToPromotionGroups) {
		this.promotionToPromotionGroups = promotionToPromotionGroups;
	}

	public Set getPromotionUsages() {
		return this.promotionUsages;
	}

	public void setPromotionUsages(Set promotionUsages) {
		this.promotionUsages = promotionUsages;
	}

	public Set getDiscountByItems() {
		return this.discountByItems;
	}

	public void setDiscountByItems(Set discountByItems) {
		this.discountByItems = discountByItems;
	}

	public Set getDiscountByInvoices() {
		return this.discountByInvoices;
	}

	public void setDiscountByInvoices(Set discountByInvoices) {
		this.discountByInvoices = discountByInvoices;
	}

	public Set getRestaurantPromotions() {
		return this.restaurantPromotions;
	}

	public void setRestaurantPromotions(Set restaurantPromotions) {
		this.restaurantPromotions = restaurantPromotions;
	}

}
