package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rates generated by hbm2java
 */
@Entity
@Table(name = "rates", catalog = "posbravo")
public class Rates implements java.io.Serializable {

	private Integer ratesId;
	private BigDecimal hourRates;
	private BigDecimal overTimeRates;
	private BigDecimal flatRates;

	public Rates() {
	}

	public Rates(BigDecimal hourRates, BigDecimal overTimeRates,
			BigDecimal flatRates) {
		this.hourRates = hourRates;
		this.overTimeRates = overTimeRates;
		this.flatRates = flatRates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RatesId", unique = true, nullable = false)
	public Integer getRatesId() {
		return this.ratesId;
	}

	public void setRatesId(Integer ratesId) {
		this.ratesId = ratesId;
	}

	@Column(name = "HourRates", scale = 4)
	public BigDecimal getHourRates() {
		return this.hourRates;
	}

	public void setHourRates(BigDecimal hourRates) {
		this.hourRates = hourRates;
	}

	@Column(name = "OverTimeRates", scale = 4)
	public BigDecimal getOverTimeRates() {
		return this.overTimeRates;
	}

	public void setOverTimeRates(BigDecimal overTimeRates) {
		this.overTimeRates = overTimeRates;
	}

	@Column(name = "FlatRates", scale = 4)
	public BigDecimal getFlatRates() {
		return this.flatRates;
	}

	public void setFlatRates(BigDecimal flatRates) {
		this.flatRates = flatRates;
	}

}
