package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * Residence generated by hbm2java
 */
public class Residence implements java.io.Serializable {

	private Integer residenceId;
	private User user;
	private Address address;

	public Residence() {
	}

	public Residence(User user, Address address) {
		this.user = user;
		this.address = address;
	}

	public Integer getResidenceId() {
		return this.residenceId;
	}

	public void setResidenceId(Integer residenceId) {
		this.residenceId = residenceId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

}
