package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Residence generated by hbm2java
 */
@Entity
@Table(name = "residence", catalog = "posbravo")
public class Residence implements java.io.Serializable {

	private ResidenceId id;

	public Residence() {
	}

	public Residence(ResidenceId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "addressId", column = @Column(name = "AddressId")),
			@AttributeOverride(name = "customerId", column = @Column(name = "CustomerID")) })
	public ResidenceId getId() {
		return this.id;
	}

	public void setId(ResidenceId id) {
		this.id = id;
	}

}
