package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * RestaurantPromotion generated by hbm2java
 */
public class RestaurantPromotion implements java.io.Serializable {

	private Integer restaurantPromotionId;
	private Restaurant restaurant;
	private Promotion promotion;

	public RestaurantPromotion() {
	}

	public RestaurantPromotion(Restaurant restaurant, Promotion promotion) {
		this.restaurant = restaurant;
		this.promotion = promotion;
	}

	public Integer getRestaurantPromotionId() {
		return this.restaurantPromotionId;
	}

	public void setRestaurantPromotionId(Integer restaurantPromotionId) {
		this.restaurantPromotionId = restaurantPromotionId;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

}
