package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * RestaurantMenu generated by hbm2java
 */
public class RestaurantMenu implements java.io.Serializable {

	private Integer restaurantMenuId;
	private Restaurant restaurant;
	private Menu menu;

	public RestaurantMenu() {
	}

	public RestaurantMenu(Restaurant restaurant, Menu menu) {
		this.restaurant = restaurant;
		this.menu = menu;
	}

	public Integer getRestaurantMenuId() {
		return this.restaurantMenuId;
	}

	public void setRestaurantMenuId(Integer restaurantMenuId) {
		this.restaurantMenuId = restaurantMenuId;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

}
