package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer roleId;
	private AccessControl accessControl;
	private String roleCategory;
	private Set userRoles = new HashSet(0);

	public Role() {
	}

	public Role(AccessControl accessControl, String roleCategory) {
		this.accessControl = accessControl;
		this.roleCategory = roleCategory;
	}

	public Role(AccessControl accessControl, String roleCategory, Set userRoles) {
		this.accessControl = accessControl;
		this.roleCategory = roleCategory;
		this.userRoles = userRoles;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public AccessControl getAccessControl() {
		return this.accessControl;
	}

	public void setAccessControl(AccessControl accessControl) {
		this.accessControl = accessControl;
	}

	public String getRoleCategory() {
		return this.roleCategory;
	}

	public void setRoleCategory(String roleCategory) {
		this.roleCategory = roleCategory;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
