package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SecurityQa generated by hbm2java
 */
@Entity
@Table(name = "security_qa", catalog = "posbravo")
public class SecurityQa implements java.io.Serializable {

	private Integer securityQaid;
	private Integer userId;
	private String securityQuestion;
	private String securityAnswer;

	public SecurityQa() {
	}

	public SecurityQa(Integer userId, String securityQuestion,
			String securityAnswer) {
		this.userId = userId;
		this.securityQuestion = securityQuestion;
		this.securityAnswer = securityAnswer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SecurityQAID", unique = true, nullable = false)
	public Integer getSecurityQaid() {
		return this.securityQaid;
	}

	public void setSecurityQaid(Integer securityQaid) {
		this.securityQaid = securityQaid;
	}

	@Column(name = "UserID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "SecurityQuestion")
	public String getSecurityQuestion() {
		return this.securityQuestion;
	}

	public void setSecurityQuestion(String securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	@Column(name = "SecurityAnswer")
	public String getSecurityAnswer() {
		return this.securityAnswer;
	}

	public void setSecurityAnswer(String securityAnswer) {
		this.securityAnswer = securityAnswer;
	}

}
