package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	private Integer serviceId;
	private Labor labor;
	private ServiceType serviceType;
	private Date timeStarted;
	private Date timeEnded;
	private Set cartItems = new HashSet(0);

	public Service() {
	}

	public Service(Labor labor, ServiceType serviceType, Date timeStarted,
			Date timeEnded, Set cartItems) {
		this.labor = labor;
		this.serviceType = serviceType;
		this.timeStarted = timeStarted;
		this.timeEnded = timeEnded;
		this.cartItems = cartItems;
	}

	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	public Labor getLabor() {
		return this.labor;
	}

	public void setLabor(Labor labor) {
		this.labor = labor;
	}

	public ServiceType getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(ServiceType serviceType) {
		this.serviceType = serviceType;
	}

	public Date getTimeStarted() {
		return this.timeStarted;
	}

	public void setTimeStarted(Date timeStarted) {
		this.timeStarted = timeStarted;
	}

	public Date getTimeEnded() {
		return this.timeEnded;
	}

	public void setTimeEnded(Date timeEnded) {
		this.timeEnded = timeEnded;
	}

	public Set getCartItems() {
		return this.cartItems;
	}

	public void setCartItems(Set cartItems) {
		this.cartItems = cartItems;
	}

}
