package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "posbravo")
public class Service implements java.io.Serializable {

	private Integer serviceId;
	private Date startTime;
	private Date endTime;
	private String laborId;

	public Service() {
	}

	public Service(Date startTime, Date endTime, String laborId) {
		this.startTime = startTime;
		this.endTime = endTime;
		this.laborId = laborId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ServiceId", unique = true, nullable = false)
	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartTime", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndTime", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "LaborId")
	public String getLaborId() {
		return this.laborId;
	}

	public void setLaborId(String laborId) {
		this.laborId = laborId;
	}

}
