package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ShippingClass generated by hbm2java
 */
public class ShippingClass implements java.io.Serializable {

	private Integer shippingClassId;
	private String class_;
	private String description;
	private Date dateLastModified;
	private Date dateAdded;
	private Set invoices = new HashSet(0);
	private Set shippings = new HashSet(0);

	public ShippingClass() {
	}

	public ShippingClass(String class_, Date dateLastModified, Date dateAdded) {
		this.class_ = class_;
		this.dateLastModified = dateLastModified;
		this.dateAdded = dateAdded;
	}

	public ShippingClass(String class_, String description,
			Date dateLastModified, Date dateAdded, Set invoices, Set shippings) {
		this.class_ = class_;
		this.description = description;
		this.dateLastModified = dateLastModified;
		this.dateAdded = dateAdded;
		this.invoices = invoices;
		this.shippings = shippings;
	}

	public Integer getShippingClassId() {
		return this.shippingClassId;
	}

	public void setShippingClassId(Integer shippingClassId) {
		this.shippingClassId = shippingClassId;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDateLastModified() {
		return this.dateLastModified;
	}

	public void setDateLastModified(Date dateLastModified) {
		this.dateLastModified = dateLastModified;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public Set getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set invoices) {
		this.invoices = invoices;
	}

	public Set getShippings() {
		return this.shippings;
	}

	public void setShippings(Set shippings) {
		this.shippings = shippings;
	}

}
