package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shipping generated by hbm2java
 */
@Entity
@Table(name = "shipping", catalog = "posbravo")
public class Shipping implements java.io.Serializable {

	private Integer shippingId;
	private Integer rate;
	private String shippingType;
	private String shippingClassId;
	private Date lastModified;
	private Date dateAdded;

	public Shipping() {
	}

	public Shipping(Integer rate, String shippingType, String shippingClassId,
			Date lastModified, Date dateAdded) {
		this.rate = rate;
		this.shippingType = shippingType;
		this.shippingClassId = shippingClassId;
		this.lastModified = lastModified;
		this.dateAdded = dateAdded;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ShippingID", unique = true, nullable = false)
	public Integer getShippingId() {
		return this.shippingId;
	}

	public void setShippingId(Integer shippingId) {
		this.shippingId = shippingId;
	}

	@Column(name = "Rate")
	public Integer getRate() {
		return this.rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}

	@Column(name = "ShippingType")
	public String getShippingType() {
		return this.shippingType;
	}

	public void setShippingType(String shippingType) {
		this.shippingType = shippingType;
	}

	@Column(name = "ShippingClassID")
	public String getShippingClassId() {
		return this.shippingClassId;
	}

	public void setShippingClassId(String shippingClassId) {
		this.shippingClassId = shippingClassId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModified", length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateAdded", length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
