package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tax generated by hbm2java
 */
@Entity
@Table(name = "tax", catalog = "posbravo")
public class Tax implements java.io.Serializable {

	private Integer taxId;
	private String state;
	private Integer rate;
	private String taxType;
	private Date lastModified;
	private Date dateAdded;
	private Integer taxClassId;

	public Tax() {
	}

	public Tax(String state, Integer rate, String taxType, Date lastModified,
			Date dateAdded, Integer taxClassId) {
		this.state = state;
		this.rate = rate;
		this.taxType = taxType;
		this.lastModified = lastModified;
		this.dateAdded = dateAdded;
		this.taxClassId = taxClassId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TaxID", unique = true, nullable = false)
	public Integer getTaxId() {
		return this.taxId;
	}

	public void setTaxId(Integer taxId) {
		this.taxId = taxId;
	}

	@Column(name = "State")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Rate")
	public Integer getRate() {
		return this.rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}

	@Column(name = "TaxType")
	public String getTaxType() {
		return this.taxType;
	}

	public void setTaxType(String taxType) {
		this.taxType = taxType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModified", length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateAdded", length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Column(name = "TaxClassID")
	public Integer getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(Integer taxClassId) {
		this.taxClassId = taxClassId;
	}

}
