package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tax generated by hbm2java
 */
public class Tax implements java.io.Serializable {

	private Integer taxId;
	private TaxClass taxClass;
	private String state;
	private BigDecimal rate;
	private String type;
	private Date dateLastModified;
	private Date dateAdded;

	public Tax() {
	}

	public Tax(TaxClass taxClass, String state, BigDecimal rate,
			Date dateLastModified, Date dateAdded) {
		this.taxClass = taxClass;
		this.state = state;
		this.rate = rate;
		this.dateLastModified = dateLastModified;
		this.dateAdded = dateAdded;
	}

	public Tax(TaxClass taxClass, String state, BigDecimal rate, String type,
			Date dateLastModified, Date dateAdded) {
		this.taxClass = taxClass;
		this.state = state;
		this.rate = rate;
		this.type = type;
		this.dateLastModified = dateLastModified;
		this.dateAdded = dateAdded;
	}

	public Integer getTaxId() {
		return this.taxId;
	}

	public void setTaxId(Integer taxId) {
		this.taxId = taxId;
	}

	public TaxClass getTaxClass() {
		return this.taxClass;
	}

	public void setTaxClass(TaxClass taxClass) {
		this.taxClass = taxClass;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getDateLastModified() {
		return this.dateLastModified;
	}

	public void setDateLastModified(Date dateLastModified) {
		this.dateLastModified = dateLastModified;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
