package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TaxClass generated by hbm2java
 */
public class TaxClass implements java.io.Serializable {

	private Integer taxClassId;
	private String class_;
	private String description;
	private Date dateLastModified;
	private Date dateAdded;
	private Set products = new HashSet(0);
	private Set taxes = new HashSet(0);

	public TaxClass() {
	}

	public TaxClass(String class_, Date dateLastModified, Date dateAdded) {
		this.class_ = class_;
		this.dateLastModified = dateLastModified;
		this.dateAdded = dateAdded;
	}

	public TaxClass(String class_, String description, Date dateLastModified,
			Date dateAdded, Set products, Set taxes) {
		this.class_ = class_;
		this.description = description;
		this.dateLastModified = dateLastModified;
		this.dateAdded = dateAdded;
		this.products = products;
		this.taxes = taxes;
	}

	public Integer getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(Integer taxClassId) {
		this.taxClassId = taxClassId;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDateLastModified() {
		return this.dateLastModified;
	}

	public void setDateLastModified(Date dateLastModified) {
		this.dateLastModified = dateLastModified;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

	public Set getTaxes() {
		return this.taxes;
	}

	public void setTaxes(Set taxes) {
		this.taxes = taxes;
	}

}
