package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TransactionStatus generated by hbm2java
 */
@Entity
@Table(name = "transaction_status", catalog = "posbravo")
public class TransactionStatus implements java.io.Serializable {

	private TransactionStatusId id;

	public TransactionStatus() {
	}

	public TransactionStatus(TransactionStatusId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tranStatusId", column = @Column(name = "TranStatusID", nullable = false)),
			@AttributeOverride(name = "status", column = @Column(name = "Status")),
			@AttributeOverride(name = "lastModified", column = @Column(name = "LastModified", length = 19)) })
	public TransactionStatusId getId() {
		return this.id;
	}

	public void setId(TransactionStatusId id) {
		this.id = id;
	}

}
