package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", catalog = "posbravo")
public class Transaction implements java.io.Serializable {

	private Integer transStatusId;
	private Integer invoiceNo;
	private Integer purchaseId;

	public Transaction() {
	}

	public Transaction(Integer invoiceNo, Integer purchaseId) {
		this.invoiceNo = invoiceNo;
		this.purchaseId = purchaseId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TransStatusID", unique = true, nullable = false)
	public Integer getTransStatusId() {
		return this.transStatusId;
	}

	public void setTransStatusId(Integer transStatusId) {
		this.transStatusId = transStatusId;
	}

	@Column(name = "InvoiceNo")
	public Integer getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(Integer invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "PurchaseId")
	public Integer getPurchaseId() {
		return this.purchaseId;
	}

	public void setPurchaseId(Integer purchaseId) {
		this.purchaseId = purchaseId;
	}

}
