package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransactionStatusId generated by hbm2java
 */
@Embeddable
public class TransactionStatusId implements java.io.Serializable {

	private int tranStatusId;
	private String status;
	private Date lastModified;

	public TransactionStatusId() {
	}

	public TransactionStatusId(int tranStatusId) {
		this.tranStatusId = tranStatusId;
	}

	public TransactionStatusId(int tranStatusId, String status,
			Date lastModified) {
		this.tranStatusId = tranStatusId;
		this.status = status;
		this.lastModified = lastModified;
	}

	@Column(name = "TranStatusID", nullable = false)
	public int getTranStatusId() {
		return this.tranStatusId;
	}

	public void setTranStatusId(int tranStatusId) {
		this.tranStatusId = tranStatusId;
	}

	@Column(name = "Status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "LastModified", length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionStatusId))
			return false;
		TransactionStatusId castOther = (TransactionStatusId) other;

		return (this.getTranStatusId() == castOther.getTranStatusId())
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getLastModified() == castOther.getLastModified()) || (this
						.getLastModified() != null
						&& castOther.getLastModified() != null && this
						.getLastModified().equals(castOther.getLastModified())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTranStatusId();
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37
				* result
				+ (getLastModified() == null ? 0 : this.getLastModified()
						.hashCode());
		return result;
	}

}
