package com.posbravo.model;

// Generated Jan 31, 2014 8:16:08 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserInRole generated by hbm2java
 */
@Entity
@Table(name = "user_in_role", catalog = "posbravo")
public class UserInRole implements java.io.Serializable {

	private UserInRoleId id;

	public UserInRole() {
	}

	public UserInRole(UserInRoleId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "UserID")),
			@AttributeOverride(name = "roleId", column = @Column(name = "RoleID")) })
	public UserInRoleId getId() {
		return this.id;
	}

	public void setId(UserInRoleId id) {
		this.id = id;
	}

}
