package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String salutation;
	private String firstName;
	private String lastName;
	private Integer ssn;
	private String gender;
	private Date dob;
	private Date dateCreated;
	private Date dateLastModified;
	private Set userPromotions = new HashSet(0);
	private Set residences = new HashSet(0);
	private Set contacts = new HashSet(0);
	private Set deliveriesForCourierId = new HashSet(0);
	private Set userRestaurants = new HashSet(0);
	private Set deliveriesForRecipientId = new HashSet(0);
	private Set promotionUsages = new HashSet(0);
	private Set userRoles = new HashSet(0);
	private Set carts = new HashSet(0);
	private Set authentications = new HashSet(0);
	private Set securityQuestions = new HashSet(0);

	public User() {
	}

	public User(Date dateCreated, Date dateLastModified) {
		this.dateCreated = dateCreated;
		this.dateLastModified = dateLastModified;
	}

	public User(String salutation, String firstName, String lastName,
			Integer ssn, String gender, Date dob, Date dateCreated,
			Date dateLastModified, Set userPromotions, Set residences,
			Set contacts, Set deliveriesForCourierId, Set userRestaurants,
			Set deliveriesForRecipientId, Set promotionUsages, Set userRoles,
			Set carts, Set authentications, Set securityQuestions) {
		this.salutation = salutation;
		this.firstName = firstName;
		this.lastName = lastName;
		this.ssn = ssn;
		this.gender = gender;
		this.dob = dob;
		this.dateCreated = dateCreated;
		this.dateLastModified = dateLastModified;
		this.userPromotions = userPromotions;
		this.residences = residences;
		this.contacts = contacts;
		this.deliveriesForCourierId = deliveriesForCourierId;
		this.userRestaurants = userRestaurants;
		this.deliveriesForRecipientId = deliveriesForRecipientId;
		this.promotionUsages = promotionUsages;
		this.userRoles = userRoles;
		this.carts = carts;
		this.authentications = authentications;
		this.securityQuestions = securityQuestions;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Integer getSsn() {
		return this.ssn;
	}

	public void setSsn(Integer ssn) {
		this.ssn = ssn;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateLastModified() {
		return this.dateLastModified;
	}

	public void setDateLastModified(Date dateLastModified) {
		this.dateLastModified = dateLastModified;
	}

	public Set getUserPromotions() {
		return this.userPromotions;
	}

	public void setUserPromotions(Set userPromotions) {
		this.userPromotions = userPromotions;
	}

	public Set getResidences() {
		return this.residences;
	}

	public void setResidences(Set residences) {
		this.residences = residences;
	}

	public Set getContacts() {
		return this.contacts;
	}

	public void setContacts(Set contacts) {
		this.contacts = contacts;
	}

	public Set getDeliveriesForCourierId() {
		return this.deliveriesForCourierId;
	}

	public void setDeliveriesForCourierId(Set deliveriesForCourierId) {
		this.deliveriesForCourierId = deliveriesForCourierId;
	}

	public Set getUserRestaurants() {
		return this.userRestaurants;
	}

	public void setUserRestaurants(Set userRestaurants) {
		this.userRestaurants = userRestaurants;
	}

	public Set getDeliveriesForRecipientId() {
		return this.deliveriesForRecipientId;
	}

	public void setDeliveriesForRecipientId(Set deliveriesForRecipientId) {
		this.deliveriesForRecipientId = deliveriesForRecipientId;
	}

	public Set getPromotionUsages() {
		return this.promotionUsages;
	}

	public void setPromotionUsages(Set promotionUsages) {
		this.promotionUsages = promotionUsages;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

	public Set getCarts() {
		return this.carts;
	}

	public void setCarts(Set carts) {
		this.carts = carts;
	}

	public Set getAuthentications() {
		return this.authentications;
	}

	public void setAuthentications(Set authentications) {
		this.authentications = authentications;
	}

	public Set getSecurityQuestions() {
		return this.securityQuestions;
	}

	public void setSecurityQuestions(Set securityQuestions) {
		this.securityQuestions = securityQuestions;
	}

}
