package com.posbravo.model;

// Generated Jun 10, 2014 6:20:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserRestaurant generated by hbm2java
 */
public class UserRestaurant implements java.io.Serializable {

	private Integer userRestaurantId;
	private Restaurant restaurant;
	private User user;

	public UserRestaurant() {
	}

	public UserRestaurant(Restaurant restaurant, User user) {
		this.restaurant = restaurant;
		this.user = user;
	}

	public Integer getUserRestaurantId() {
		return this.userRestaurantId;
	}

	public void setUserRestaurantId(Integer userRestaurantId) {
		this.userRestaurantId = userRestaurantId;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
